// Ambergris 0.3.0 (tokens.json, commit c92c190). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Ambergris.
// Plot.plot({color: {range: ambergrisDark}}) or d3.scaleOrdinal(ambergrisDark).
export const ambergrisScale = ["#FAFBFD","#F3F5F7","#EAEDEF","#DCDFE3","#C8CBD0","#AEB2B7","#8D9298","#72777D","#5C6168","#42484E","#2B3037","#1A1F26","#0C1117"];
export const ambergrisDark = ["#5BB6B1","#13998D","#2BA6C6","#6FAEF3","#A0BAFE","#C3CCFE"];
export const ambergrisSequentialDark = ["#13998D","#2BA6C6","#6FAEF3","#A0BAFE","#C3CCFE"];
export const ambergrisPlotDark = {"bg":"#1A1F26","grid":"#2B3037","text":"#EAEDEF","muted":"#AEB2B7"};
export const ambergrisLight = ["#1E807B","#2EA094","#0587A4","#236AAF","#304BB0","#3428AA"];
export const ambergrisSequentialLight = ["#2EA094","#0587A4","#236AAF","#304BB0","#3428AA"];
export const ambergrisPlotLight = {"bg":"#FAFBFD","grid":"#DCDFE3","text":"#1A1F26","muted":"#5C6168"};
export default ambergrisDark;
