// Glauca 0.1.0 (src/glauca.json, commit 1e66632). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Glauca.
// Merge into tailwind.config.js, or require() this file and spread it.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "frost": {
          "charta": "#F0F4F6",
          "pruina": "#E8EEF2",
          "nebula": "#93B7C9",
          "cinis": "#8C8C8C",
          "spuma": "#4D7391",
          "vadum": "#2B4356",
          "petra": "#1F2932",
          "caligo": "#142430",
          "umbra": "#171F26",
          "pix": "#10161C",
          "ferrum": "#0B1218"
        },
        "dies": {
          "DEFAULT": "#0B62CF",
          "light": "#0B62CF",
          "dark": "#007AFF"
        },
        "aer": {
          "DEFAULT": "#084B96",
          "light": "#084B96",
          "dark": "#6CB2FF"
        },
        "imum": {
          "DEFAULT": "#084B96",
          "light": "#084B96",
          "dark": "#084B96"
        },
        "folium": {
          "DEFAULT": "#3C6E38",
          "light": "#3C6E38",
          "dark": "#62BA46"
        },
        "bacca": {
          "DEFAULT": "#784A4D",
          "light": "#784A4D",
          "dark": "#C96A6A"
        },
        "viola": {
          "DEFAULT": "#6B588B",
          "light": "#6B588B",
          "dark": "#B184DB"
        },
        "lacus": {
          "DEFAULT": "#33668B",
          "light": "#33668B",
          "dark": "#4A9EDB"
        },
        "unda": {
          "DEFAULT": "#306972",
          "light": "#306972",
          "dark": "#45A3AD"
        },
        "light": {
          "bg": "#F0F4F6",
          "surface": "#F7FAFB",
          "text": "#16222A",
          "text-muted": "#55646D",
          "text-subtle": "#55646D",
          "border": "#CDD7DC",
          "link": "#0B62CF",
          "link-hover": "#084B96",
          "accent": "#0B62CF",
          "on-accent": "#F2F7FB",
          "button": "#0B62CF",
          "on-button": "#F2F7FB",
          "focus": "#0B62CF",
          "selection": "#B7CDD6"
        },
        "dark": {
          "bg": "#10161C",
          "surface": "#171F26",
          "text": "#E8EEF2",
          "text-muted": "#8C8C8C",
          "text-subtle": "#8C8C8C",
          "border": "#2A3540",
          "link": "#3D97FF",
          "link-hover": "#6CB2FF",
          "accent": "#3D97FF",
          "on-accent": "#0B1218",
          "button": "#3D97FF",
          "on-button": "#0B1218",
          "focus": "#6CB2FF",
          "selection": "#2B4356"
        }
      }
    }
  }
};
