# Ambergris 0.3.0 (tokens.json, commit c92c190). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Ambergris.
# import this module and call register_cmaps() once.
from matplotlib.colors import LinearSegmentedColormap
import matplotlib as mpl

SCALE = {"grey_000": "#FAFBFD", "grey_050": "#F3F5F7", "grey_100": "#EAEDEF", "grey_200": "#DCDFE3", "grey_300": "#C8CBD0", "grey_400": "#AEB2B7", "grey_500": "#8D9298", "grey_600": "#72777D", "grey_700": "#5C6168", "grey_800": "#42484E", "grey_900": "#2B3037", "grey_950": "#1A1F26", "grey_1000": "#0C1117"}
ACCENTS_DARK = {"accent": "#5BB6B1", "sweep_1": "#13998D", "sweep_2": "#2BA6C6", "sweep_3": "#6FAEF3", "sweep_4": "#A0BAFE", "sweep_5": "#C3CCFE"}
SERIES_DARK = ["#5BB6B1", "#13998D", "#2BA6C6", "#6FAEF3", "#A0BAFE", "#C3CCFE"]
SEQUENTIAL_DARK = ["#13998D", "#2BA6C6", "#6FAEF3", "#A0BAFE", "#C3CCFE"]
ACCENTS_LIGHT = {"accent": "#1E807B", "sweep_1": "#2EA094", "sweep_2": "#0587A4", "sweep_3": "#236AAF", "sweep_4": "#304BB0", "sweep_5": "#3428AA"}
SERIES_LIGHT = ["#1E807B", "#2EA094", "#0587A4", "#236AAF", "#304BB0", "#3428AA"]
SEQUENTIAL_LIGHT = ["#2EA094", "#0587A4", "#236AAF", "#304BB0", "#3428AA"]


def register_cmaps():
    """Register ambergris_seq_<mode> (and _div where the family has one)."""
    mpl.colormaps.register(LinearSegmentedColormap.from_list("ambergris_seq_dark", SEQUENTIAL_DARK), force=True)
    mpl.colormaps.register(LinearSegmentedColormap.from_list("ambergris_seq_light", SEQUENTIAL_LIGHT), force=True)


def use(mode="dark"):
    """Apply the series cycle for a mode."""
    mpl.rcParams["axes.prop_cycle"] = mpl.cycler(color=globals()["SERIES_" + mode.upper()])
