# Try-Works 1.0.0 (src/try-works.json, commit 400dd91). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Try-Works.
# source() this file; needs ggplot2.

try_works_scale <- c(whale_whale = "#F1EFE9", whale_bone = "#DEE7E4", sea_foam = "#8FB6BD", whale_gull = "#97A0A4", sea_spray = "#4D7680", sea_swell = "#2C4953", ground_deck = "#232B32", sea_trough = "#14242C", ground_hold = "#1B2127", ground_pitch = "#12161B", ground_iron = "#11151A")

# Try-Fire (dark)
try_works_dark <- list(
  bg = "#12161B", surface = "#1B2127", text = "#F1EFE9", muted = "#97A0A4",
  grid = "#2C3640", border = "#2C3640", accent = "#C9651D", link = "#C9651D"
)
try_works_accents_dark <- c(ember = "#C9651D", flame = "#E0832A", oil = "#9A4A16", kelp = "#86A87F", brick = "#D06A52", dusk = "#A487BA", tide = "#5F93B0", shoal = "#5F97A0")
try_works_series_dark <- c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "#D55E00", "#56B4E9", "#F0E442")
try_works_sequential_dark <- c("#E4F5FB", "#B3E0EE", "#7EC4D7", "#48A0B7", "#0A7B93", "#00576C", "#003542")
try_works_diverging_dark <- c("#00576E", "#287D93", "#72A9B4", "#BBD7D9", "#F1EEE6", "#E7CCAE", "#DA9B6A", "#C26D32", "#984A1A")

# True Lamp (light)
try_works_light <- list(
  bg = "#DEE7E4", surface = "#E7EFEB", text = "#18272B", muted = "#52646A",
  grid = "#DCE5E1", border = "#C4D2CD", accent = "#9E5017", link = "#9E5017"
)
try_works_accents_light <- c(ember = "#9E5017", flame = "#7A3A10", oil = "#7A3A10", kelp = "#4F6855", brick = "#7D4C40", dusk = "#655C7A", tide = "#3F6274", shoal = "#3F656B")
try_works_series_light <- c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "#D55E00", "#56B4E9", "#F0E442")
try_works_sequential_light <- c("#E4F5FB", "#B3E0EE", "#7EC4D7", "#48A0B7", "#0A7B93", "#00576C", "#003542")
try_works_diverging_light <- c("#00576E", "#287D93", "#72A9B4", "#BBD7D9", "#F1EEE6", "#E7CCAE", "#DA9B6A", "#C26D32", "#984A1A")

#' Discrete colour and fill scales
scale_colour_try_works_d <- function(mode = "dark", ...) {
  values <- get(paste0("try_works_series_", mode))
  ggplot2::scale_colour_manual(values = unname(values), ...)
}
scale_color_try_works_d <- scale_colour_try_works_d
scale_fill_try_works_d <- function(mode = "dark", ...) {
  values <- get(paste0("try_works_series_", mode))
  ggplot2::scale_fill_manual(values = unname(values), ...)
}

#' Continuous (sequential) scales
scale_colour_try_works_c <- function(mode = "dark", ...) {
  ggplot2::scale_colour_gradientn(colours = get(paste0("try_works_sequential_", mode)), ...)
}
scale_color_try_works_c <- scale_colour_try_works_c
scale_fill_try_works_c <- function(mode = "dark", ...) {
  ggplot2::scale_fill_gradientn(colours = get(paste0("try_works_sequential_", mode)), ...)
}

#' Diverging scales
scale_colour_try_works_div <- function(mode = "dark", ...) {
  ggplot2::scale_colour_gradientn(colours = get(paste0("try_works_diverging_", mode)), ...)
}
scale_fill_try_works_div <- function(mode = "dark", ...) {
  ggplot2::scale_fill_gradientn(colours = get(paste0("try_works_diverging_", mode)), ...)
}

#' A theme on the family's plot surface
theme_try_works <- function(mode = "dark", base_size = 11) {
  m <- get(paste0("try_works_", mode))
  ggplot2::theme_minimal(base_size = base_size) +
    ggplot2::theme(
      plot.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      panel.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      panel.grid.major = ggplot2::element_line(colour = m$grid),
      panel.grid.minor = ggplot2::element_blank(),
      text = ggplot2::element_text(colour = m$text),
      axis.text = ggplot2::element_text(colour = m$muted),
      legend.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      strip.text = ggplot2::element_text(colour = m$text)
    )
}
