# Pequod 0.2.0-alpha (pequod.json, commit 619982d). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Pequod.
# source() this file; needs ggplot2.

pequod_scale <- c(log_50 = "#F7F3EE", log_100 = "#EAE1D7", log_150 = "#DBC9B6", log_200 = "#CFAD8E", log_300 = "#BD8C68", log_400 = "#A16E50", log_500 = "#835A49", log_600 = "#335260", log_700 = "#163F54", log_800 = "#0D2F42", log_900 = "#0C222F", log_950 = "#0B1720")

# Below deck (dark)
pequod_dark <- list(
  bg = "#0B1720", surface = "#0D2F42", text = "#EAE1D7", muted = "#BD8C68",
  grid = "#163F54", border = "#163F54", accent = "#BD8C68", link = "#BD8C68"
)
pequod_accents_dark <- c(ahab = "#E3877C", starbuck = "#A6DFFF", queequeg = "#838CCF", pip = "#DEC577", ishmael = "#BFBBB6", stubb = "#FFD9BB", tashtego = "#82C4A2", daggoo = "#A17069")
pequod_series_dark <- c("#E3877C", "#A6DFFF", "#838CCF", "#DEC577", "#BFBBB6", "#FFD9BB", "#82C4A2", "#A17069")
pequod_sequential_dark <- c("#F7F3EE", "#EAE1D7", "#DBC9B6", "#CFAD8E", "#BD8C68", "#A16E50", "#835A49", "#335260", "#163F54", "#0D2F42", "#0C222F", "#0B1720")

# Parchment (light)
pequod_light <- list(
  bg = "#EAE1D7", surface = "#DBC9B6", text = "#0D2F42", muted = "#335260",
  grid = "#CFAD8E", border = "#CFAD8E", accent = "#163F54", link = "#163F54"
)
pequod_accents_light <- c(ahab = "#A83732", starbuck = "#0082B1", queequeg = "#253E82", pip = "#6A4A00", ishmael = "#76716B", stubb = "#CA6435", tashtego = "#177C55", daggoo = "#552823")
pequod_series_light <- c("#A83732", "#0082B1", "#253E82", "#6A4A00", "#76716B", "#CA6435", "#177C55", "#552823")
pequod_sequential_light <- c("#F7F3EE", "#EAE1D7", "#DBC9B6", "#CFAD8E", "#BD8C68", "#A16E50", "#835A49", "#335260", "#163F54", "#0D2F42", "#0C222F", "#0B1720")

#' Discrete colour and fill scales
scale_colour_pequod_d <- function(mode = "dark", ...) {
  values <- get(paste0("pequod_series_", mode))
  ggplot2::scale_colour_manual(values = unname(values), ...)
}
scale_color_pequod_d <- scale_colour_pequod_d
scale_fill_pequod_d <- function(mode = "dark", ...) {
  values <- get(paste0("pequod_series_", mode))
  ggplot2::scale_fill_manual(values = unname(values), ...)
}

#' Continuous (sequential) scales
scale_colour_pequod_c <- function(mode = "dark", ...) {
  ggplot2::scale_colour_gradientn(colours = get(paste0("pequod_sequential_", mode)), ...)
}
scale_color_pequod_c <- scale_colour_pequod_c
scale_fill_pequod_c <- function(mode = "dark", ...) {
  ggplot2::scale_fill_gradientn(colours = get(paste0("pequod_sequential_", mode)), ...)
}

#' A theme on the family's plot surface
theme_pequod <- function(mode = "dark", base_size = 11) {
  m <- get(paste0("pequod_", mode))
  ggplot2::theme_minimal(base_size = base_size) +
    ggplot2::theme(
      plot.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      panel.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      panel.grid.major = ggplot2::element_line(colour = m$grid),
      panel.grid.minor = ggplot2::element_blank(),
      text = ggplot2::element_text(colour = m$text),
      axis.text = ggplot2::element_text(colour = m$muted),
      legend.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      strip.text = ggplot2::element_text(colour = m$text)
    )
}
