-- Ambergris 0.3.0 (tokens.json, commit c92c190). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Ambergris.
-- Copy to ~/.config/nvim/colors/ambergris-light.lua and :colorscheme ambergris-light

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "light"
vim.g.colors_name = "ambergris-light"

local function hi(group, spec) vim.api.nvim_set_hl(0, group, spec) end

  hi("Normal", { fg = "#1A1F26", bg = "#FAFBFD" })
  hi("NormalFloat", { fg = "#1A1F26", bg = "#EAEDEF" })
  hi("NormalNC", { fg = "#1A1F26", bg = "#FAFBFD" })
  hi("Comment", { fg = "#5C6168", italic = true })
  hi("String", { fg = "#2B3037", italic = true })
  hi("Character", { fg = "#2B3037", italic = true })
  hi("Number", { fg = "#1A1F26" })
  hi("Float", { fg = "#1A1F26" })
  hi("Boolean", { fg = "#1A1F26" })
  hi("Constant", { fg = "#1A1F26" })
  hi("Identifier", { fg = "#1A1F26" })
  hi("Function", { fg = "#0C1117" })
  hi("Statement", { fg = "#1A1F26", bold = true })
  hi("Keyword", { fg = "#1A1F26", bold = true })
  hi("Conditional", { fg = "#1A1F26", bold = true })
  hi("Repeat", { fg = "#1A1F26", bold = true })
  hi("Operator", { fg = "#42484E" })
  hi("Exception", { fg = "#1A1F26", bold = true })
  hi("PreProc", { fg = "#2B3037" })
  hi("Include", { fg = "#1A1F26", bold = true })
  hi("Define", { fg = "#2B3037" })
  hi("Macro", { fg = "#2B3037" })
  hi("Type", { fg = "#1A1F26" })
  hi("StorageClass", { fg = "#1A1F26", bold = true })
  hi("Structure", { fg = "#1A1F26" })
  hi("Typedef", { fg = "#1A1F26" })
  hi("Special", { fg = "#1A1F26" })
  hi("Delimiter", { fg = "#5C6168" })
  hi("Todo", { fg = "#FAFBFD", bg = "#0C1117", bold = true })
  hi("Underlined", { fg = "#1E807B", underline = true })
  hi("Error", { fg = "#1A1F26" })
  hi("Title", { fg = "#1A1F26", bold = true })
  hi("LineNr", { fg = "#72777D", bg = "#FAFBFD" })
  hi("CursorLineNr", { fg = "#1A1F26", bold = true })
  hi("CursorLine", { bg = "#EAEDEF" })
  hi("ColorColumn", { bg = "#EAEDEF" })
  hi("SignColumn", { bg = "#FAFBFD" })
  hi("VertSplit", { fg = "#C8CBD0" })
  hi("WinSeparator", { fg = "#C8CBD0" })
  hi("Visual", { bg = "#E7F8F6" })
  hi("Search", { fg = "#1A1F26", bg = "#2F9F99" })
  hi("IncSearch", { fg = "#FAFBFD", bg = "#0C1117" })
  hi("CurSearch", { fg = "#FAFBFD", bg = "#0C1117" })
  hi("MatchParen", { fg = "#2F9F99", bold = true, underline = true })
  hi("Pmenu", { fg = "#1A1F26", bg = "#EAEDEF" })
  hi("PmenuSel", { fg = "#1A1F26", bg = "#E7F8F6" })
  hi("PmenuSbar", { bg = "#EAEDEF" })
  hi("PmenuThumb", { bg = "#72777D" })
  hi("StatusLine", { fg = "#1A1F26", bg = "#EAEDEF" })
  hi("StatusLineNC", { fg = "#5C6168", bg = "#EAEDEF" })
  hi("TabLine", { fg = "#5C6168", bg = "#EAEDEF" })
  hi("TabLineSel", { fg = "#1A1F26", bg = "#FAFBFD", bold = true })
  hi("TabLineFill", { bg = "#EAEDEF" })
  hi("NonText", { fg = "#C8CBD0" })
  hi("Whitespace", { fg = "#C8CBD0" })
  hi("EndOfBuffer", { fg = "#FAFBFD" })
  hi("Directory", { fg = "#1E807B" })
  hi("Question", { fg = "#2B3037" })
  hi("MoreMsg", { fg = "#2B3037" })
  hi("ErrorMsg", { fg = "#1A1F26" })
  hi("WarningMsg", { fg = "#1A1F26" })
  hi("FloatBorder", { fg = "#C8CBD0", bg = "#EAEDEF" })
  hi("Cursor", { fg = "#FAFBFD", bg = "#0C1117" })
  hi("DiffAdd", { bg = "#2B3037" })
  hi("DiffDelete", { fg = "#1A1F26" })
  hi("DiffChange", { bg = "#EAEDEF" })
  hi("DiffText", { bg = "#E7F8F6" })
  hi("DiagnosticError", { fg = "#1A1F26" })
  hi("DiagnosticWarn", { fg = "#1A1F26" })
  hi("DiagnosticInfo", { fg = "#0C1117" })
  hi("DiagnosticHint", { fg = "#5C6168" })
  hi("@comment", { link = "Comment" })
  hi("@string", { link = "String" })
  hi("@number", { link = "Number" })
  hi("@keyword", { link = "Keyword" })
  hi("@function", { link = "Function" })
  hi("@function.call", { link = "Function" })
  hi("@type", { link = "Type" })
  hi("@constant", { link = "Constant" })
  hi("@variable", { fg = "#1A1F26" })
  hi("@variable.parameter", { fg = "#1A1F26" })
  hi("@operator", { link = "Operator" })
  hi("@punctuation", { link = "Delimiter" })
  hi("@attribute", { fg = "#2B3037" })
  hi("@property", { fg = "#1A1F26" })
  hi("@tag", { fg = "#1A1F26", bold = true })
  hi("@markup.heading", { fg = "#1A1F26", bold = true })
  hi("@markup.link.url", { fg = "#1E807B", underline = true })
  hi("@markup.raw", { fg = "#2B3037", italic = true })

vim.g.terminal_color_0 = "#1A1F26"
vim.g.terminal_color_1 = "#CF7F79"
vim.g.terminal_color_2 = "#7BB587"
vim.g.terminal_color_3 = "#D4BC79"
vim.g.terminal_color_4 = "#72A5DE"
vim.g.terminal_color_5 = "#B893D4"
vim.g.terminal_color_6 = "#5BB6B1"
vim.g.terminal_color_7 = "#C8CBD0"
vim.g.terminal_color_8 = "#5C6168"
vim.g.terminal_color_9 = "#E7958E"
vim.g.terminal_color_10 = "#91CB9C"
vim.g.terminal_color_11 = "#E8CF8C"
vim.g.terminal_color_12 = "#88BCF6"
vim.g.terminal_color_13 = "#CEA9EB"
vim.g.terminal_color_14 = "#86CDC8"
vim.g.terminal_color_15 = "#FAFBFD"
