# Try-Works 1.0.0 (src/try-works.json, commit 400dd91). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Try-Works.
# import this module and call register_cmaps() once.
from matplotlib.colors import LinearSegmentedColormap
import matplotlib as mpl

SCALE = {"whale_whale": "#F1EFE9", "whale_bone": "#DEE7E4", "sea_foam": "#8FB6BD", "whale_gull": "#97A0A4", "sea_spray": "#4D7680", "sea_swell": "#2C4953", "ground_deck": "#232B32", "sea_trough": "#14242C", "ground_hold": "#1B2127", "ground_pitch": "#12161B", "ground_iron": "#11151A"}
ACCENTS_DARK = {"ember": "#C9651D", "flame": "#E0832A", "oil": "#9A4A16", "kelp": "#86A87F", "brick": "#D06A52", "dusk": "#A487BA", "tide": "#5F93B0", "shoal": "#5F97A0"}
SERIES_DARK = ["#E69F00", "#0072B2", "#009E73", "#CC79A7", "#D55E00", "#56B4E9", "#F0E442"]
SEQUENTIAL_DARK = ["#E4F5FB", "#B3E0EE", "#7EC4D7", "#48A0B7", "#0A7B93", "#00576C", "#003542"]
DIVERGING_DARK = ["#00576E", "#287D93", "#72A9B4", "#BBD7D9", "#F1EEE6", "#E7CCAE", "#DA9B6A", "#C26D32", "#984A1A"]
ACCENTS_LIGHT = {"ember": "#9E5017", "flame": "#7A3A10", "oil": "#7A3A10", "kelp": "#4F6855", "brick": "#7D4C40", "dusk": "#655C7A", "tide": "#3F6274", "shoal": "#3F656B"}
SERIES_LIGHT = ["#E69F00", "#0072B2", "#009E73", "#CC79A7", "#D55E00", "#56B4E9", "#F0E442"]
SEQUENTIAL_LIGHT = ["#E4F5FB", "#B3E0EE", "#7EC4D7", "#48A0B7", "#0A7B93", "#00576C", "#003542"]
DIVERGING_LIGHT = ["#00576E", "#287D93", "#72A9B4", "#BBD7D9", "#F1EEE6", "#E7CCAE", "#DA9B6A", "#C26D32", "#984A1A"]


def register_cmaps():
    """Register try_works_seq_<mode> (and _div where the family has one)."""
    mpl.colormaps.register(LinearSegmentedColormap.from_list("try_works_seq_dark", SEQUENTIAL_DARK), force=True)
    mpl.colormaps.register(LinearSegmentedColormap.from_list("try_works_div_dark", DIVERGING_DARK), force=True)
    mpl.colormaps.register(LinearSegmentedColormap.from_list("try_works_seq_light", SEQUENTIAL_LIGHT), force=True)
    mpl.colormaps.register(LinearSegmentedColormap.from_list("try_works_div_light", DIVERGING_LIGHT), force=True)


def use(mode="dark"):
    """Apply the series cycle for a mode."""
    mpl.rcParams["axes.prop_cycle"] = mpl.cycler(color=globals()["SERIES_" + mode.upper()])
