# Glauca 0.1.0 (src/glauca.json, commit 1e66632). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Glauca.
# import this module and call register_cmaps() once.
from matplotlib.colors import LinearSegmentedColormap
import matplotlib as mpl

SCALE = {"pruina_charta": "#F0F4F6", "pruina_pruina": "#E8EEF2", "glaucum_nebula": "#93B7C9", "pruina_cinis": "#8C8C8C", "glaucum_spuma": "#4D7391", "glaucum_vadum": "#2B4356", "saxum_petra": "#1F2932", "glaucum_caligo": "#142430", "saxum_umbra": "#171F26", "saxum_pix": "#10161C", "saxum_ferrum": "#0B1218"}
ACCENTS_DARK = {"dies": "#007AFF", "aer": "#6CB2FF", "imum": "#084B96", "folium": "#62BA46", "bacca": "#C96A6A", "viola": "#B184DB", "lacus": "#4A9EDB", "unda": "#45A3AD"}
SERIES_DARK = ["#E69F00", "#0072B2", "#009E73", "#CC79A7", "#D55E00", "#56B4E9", "#F0E442"]
SEQUENTIAL_DARK = ["#EAF2FC", "#C3DCF5", "#92C0EA", "#5B9EDB", "#2F7CC4", "#0B5AA0", "#063A6B"]
DIVERGING_DARK = ["#084B96", "#3672B4", "#7BA1CD", "#C0D3E6", "#F0EFE9", "#E6CDB0", "#D3A26E", "#B97435", "#8F4F16"]
ACCENTS_LIGHT = {"dies": "#0B62CF", "aer": "#084B96", "imum": "#084B96", "folium": "#3C6E38", "bacca": "#784A4D", "viola": "#6B588B", "lacus": "#33668B", "unda": "#306972"}
SERIES_LIGHT = ["#E69F00", "#0072B2", "#009E73", "#CC79A7", "#D55E00", "#56B4E9", "#F0E442"]
SEQUENTIAL_LIGHT = ["#EAF2FC", "#C3DCF5", "#92C0EA", "#5B9EDB", "#2F7CC4", "#0B5AA0", "#063A6B"]
DIVERGING_LIGHT = ["#084B96", "#3672B4", "#7BA1CD", "#C0D3E6", "#F0EFE9", "#E6CDB0", "#D3A26E", "#B97435", "#8F4F16"]


def register_cmaps():
    """Register glauca_seq_<mode> (and _div where the family has one)."""
    mpl.colormaps.register(LinearSegmentedColormap.from_list("glauca_seq_dark", SEQUENTIAL_DARK), force=True)
    mpl.colormaps.register(LinearSegmentedColormap.from_list("glauca_div_dark", DIVERGING_DARK), force=True)
    mpl.colormaps.register(LinearSegmentedColormap.from_list("glauca_seq_light", SEQUENTIAL_LIGHT), force=True)
    mpl.colormaps.register(LinearSegmentedColormap.from_list("glauca_div_light", DIVERGING_LIGHT), force=True)


def use(mode="dark"):
    """Apply the series cycle for a mode."""
    mpl.rcParams["axes.prop_cycle"] = mpl.cycler(color=globals()["SERIES_" + mode.upper()])
