// Ambergris: tokens.json. A thirteen-step cool grey ramp, a ten-step teal
// accent ramp used for interaction only, two five-stop sequential data
// sweeps (one per chart background), a dark-only ANSI block, and semantic
// themes written as {alias} references. The repository ships dark ports
// only; the light code map and light terminal here are generated by the
// rules described inline and are not audited by the family.
import {
  fromFile, fromOfficial, derived, alias, fallback, roles, syntax, terminal, contrastPick, ANSI_NAMES,
} from '../token.js';
import { terminalFromGhostty } from '../ghostty.js';
import { contrast } from '../../colour/wcag.js';
import { mix8, lower } from '../../colour/hex.js';

const FILE = 'tokens.json';

/** Resolve "{a.b.c}" references the way build.mjs does; returns the hex. */
function resolve(json, value, depth = 0) {
  if (depth > 12) throw new Error('alias cycle');
  if (typeof value !== 'string') return value.hex;
  const m = /^\{([^}]+)\}$/.exec(value.trim());
  if (!m) return value;
  const target = m[1].split('.').reduce((o, k) => (o == null ? undefined : o[k]), json);
  if (target === undefined) throw new Error(`unknown alias ${value}`);
  return resolve(json, target, depth + 1);
}

function refPath(value) {
  const m = /^\{([^}]+)\}$/.exec(String(value).trim());
  return m ? m[1] : null;
}

export function adapt({ json, files }) {
  const greyPath = (n) => `color.grey.${n}`;
  const steps = Object.entries(json.color.grey).map(([n, v]) =>
    fromFile(FILE, greyPath(n), v.hex, `grey.${n}`, `Grey ${n}`));
  const grey = (n) => steps.find((s) => s.id === `grey.${n}`);
  const accentSteps = Object.entries(json.color.accent).filter(([k]) => k !== 'comment').map(([n, v]) =>
    fromFile(FILE, `color.accent.${n}`, v.hex, `accent.${n}`, `Accent ${n}`));
  const accentStep = (n) => accentSteps.find((s) => s.id === `accent.${n}`);

  // A theme value ("{color.grey.950}" or an rgb() string) as a token.
  const themeToken = (m, key, id = key) => {
    const raw = json.theme[m][key];
    const path = refPath(raw);
    const hex = resolve(json, raw);
    if (!/^#/.test(hex)) return null; // alpha overlays are not flat colours
    const base = path && path.startsWith('color.grey.') ? grey(path.split('.').pop())
      : path && path.startsWith('color.accent.') ? accentStep(path.split('.').pop()) : null;
    return base ? alias(base, `${m}.${id}`, `${m} ${id}`) : fromFile(FILE, `theme.${m}.${key}`, hex, `${m}.${id}`, `${m} ${id}`);
  };

  const sweep = (m) => Object.entries(json.data[`sequence-on-${m}`]).map(([n, v]) =>
    fromFile(FILE, `data.sequence-on-${m}.${n}`, v.hex, `data.${m}.${n}`, `Sweep ${n} (${m})`));

  const accents = [
    { id: 'accent', label: 'Accent', hue: 'teal', tier: 'core', note: 'Interaction only: links, the current item, selection. Never severity, never decoration.',
      dark: alias(themeToken('dark', 'link'), 'accent.dark', 'Accent dark'),
      light: alias(themeToken('light', 'link'), 'accent.light', 'Accent light') },
    ...[1, 2, 3, 4, 5].map((n) => ({
      id: `sweep-${n}`, label: `Sweep ${n}`, hue: n <= 2 ? 'teal' : n === 3 ? 'blue' : 'indigo', tier: 'extended',
      note: n === 1 ? 'The data sweep is sequential only; the family rules it out for unordered groups.' : undefined,
      dark: sweep('dark')[n - 1], light: sweep('light')[n - 1],
    })),
  ];

  // Dark ground and the grey step a hex belongs to, for the mirror rule.
  const stepOf = (hex) => steps.find((s) => lower(s.hex) === lower(hex));
  const darkGround = themeToken('dark', 'ground', 'ground');
  const lightGround = themeToken('light', 'ground', 'ground');
  /**
   * Contrast-matched mirror: the grey step whose contrast on the light
   * ground is closest (in log ratio) to the contrast the dark step has on
   * the dark ground. Keeps every colour on the ramp and the reading
   * hierarchy intact; unaudited by the family.
   */
  const mirror = (darkTok, id, label) => {
    const target = Math.log(contrast(darkTok.hex, darkGround.hex));
    let best = null;
    for (const s of steps) {
      const d = Math.abs(Math.log(contrast(s.hex, lightGround.hex)) - target);
      if (!best || d < best.d) best = { s, d };
    }
    return derived(`mirror-contrast(${darkTok.id}) on ${lightGround.id}`, [darkTok, darkGround, lightGround], best.s.hex, id, label);
  };

  const zed = JSON.parse(files['ports/zed/ambergris.json']);
  const zsyn = zed.themes[0].style.syntax;
  const ZED_KEYS = {
    keyword: 'keyword', string: 'string', number: 'number', comment: 'comment', function: 'function',
    type: 'type', constant: 'constant', variable: 'variable', operator: 'operator', punctuation: 'punctuation',
    decorator: 'attribute', parameter: 'variable',
  };

  const mode = (m) => {
    const tt = (key, id) => themeToken(m, key, id);
    // The family asserts its link and body contrast against `surface`
    // (grey 000 light, grey 950 dark), so that is the reading ground here.
    const bg = tt('surface', 'bg');
    const text = tt('text-primary', 'text');
    const accent = tt('accent-line', 'accent');
    const onAccent = contrastPick(accent, bg, text, `${m}.on-accent`);
    const rolesRecord = roles({
      bg,
      surface: tt('surface-sunken', 'surface'),
      text,
      textMuted: tt('text-secondary', 'text-muted'),
      textSubtle: tt('text-tertiary', 'text-subtle'),
      border: tt('rule', 'border'),
      link: tt('link', 'link'),
      linkHover: tt('link-hover', 'link-hover'),
      accent,
      onAccent,
      button: tt('fill-solid', 'button'),
      onButton: tt('text-on-fill', 'on-button'),
      focus: tt('focus-ring', 'focus'),
      selection: tt('accent-surface', 'selection'),
    });

    const syn = {};
    for (const role of Object.keys(ZED_KEYS)) {
      const z = zsyn[ZED_KEYS[role]];
      const dark = fromOfficial('ports/zed/ambergris.json', `syntax.${ZED_KEYS[role]}.color`, z.color, `dark.syntax.${role}`, `Dark ${role}`);
      let tok = m === 'dark' ? dark : mirror(dark, `light.syntax.${role}`, `Light ${role}`);
      if (role === 'decorator') tok = fallback(tok, `${m}.syntax.decorator`, 'attribute');
      if (role === 'parameter') tok = fallback(tok, `${m}.syntax.parameter`, 'variable');
      if (z.font_style === 'italic') tok = { ...tok, style: 'italic' };
      else if (z.font_weight && z.font_weight >= 700) tok = { ...tok, style: 'bold' };
      syn[role] = tok;
    }
    const syntaxRecord = syntax(syn);

    let term;
    if (m === 'dark') {
      term = terminalFromGhostty('ports/ghostty/ambergris-dark', files['ports/ghostty/ambergris-dark'], 'dark.terminal');
    } else {
      // Generated: chrome from theme.light the way the port takes it from
      // theme.dark (cursor is the inverse surface, selection is the accent
      // at the selection-fill opacity flattened onto the ground); the ANSI
      // hues are the family's dark-tuned functional hues, reused as they are.
      const p = 'light.terminal';
      const dark = terminalFromGhostty('ports/ghostty/ambergris-dark', files['ports/ghostty/ambergris-dark'], 'dark.terminal');
      const a500 = accentStep('500');
      term = terminal({
        origin: 'generated',
        bg: alias(bg, `${p}.bg`),
        fg: alias(text, `${p}.fg`),
        cursor: alias(tt('surface-inverse', 'surface-inverse'), `${p}.cursor`),
        cursorText: alias(bg, `${p}.cursor-text`),
        selectionBg: derived(`blend(${a500.id}, 0.24, ${bg.id})`, [a500, bg], mix8(bg.hex, a500.hex, 0.24), `${p}.selection-bg`),
        selectionFg: alias(text, `${p}.selection-fg`),
        ansi: ANSI_NAMES.map((n, i) => alias(dark.ansi[i], `${p}.ansi.${n}`)),
      });
    }

    return {
      label: m === 'dark' ? 'Dark' : 'Light',
      scheme: m,
      roles: rolesRecord,
      syntax: syntaxRecord,
      terminal: term,
      dataviz: {
        categorical: [],
        categoricalNote: 'none by rule: the sweep is sequential only',
        sequential: sweep(m),
        diverging: null,
        plot: {
          bg: alias(bg, `${m}.plot.bg`),
          grid: alias(tt('rule-faint', 'rule-faint'), `${m}.plot.grid`),
          text: alias(text, `${m}.plot.text`),
          muted: alias(rolesRecord.textMuted, `${m}.plot.muted`),
        },
      },
    };
  };

  return {
    id: 'ambergris',
    name: json.meta.name,
    version: json.meta.version,
    description: json.meta.description,
    descriptionSource: 'tokens.json meta.description (the repository has no README)',
    tagline: 'Near-monochrome, one teal for interaction, a hue sweep for data.',
    repo: 'https://github.com/tiagojct/ambergris',
    homepage: null,
    changelog: null,
    licence: { tokens: 'CC-BY-4.0', code: 'MIT', stated: false, files: [] },
    tokenFile: FILE,
    rules: json.meta.rules,
    scale: { name: 'Grey', steps },
    extraScales: [{ name: 'Accent', steps: accentSteps }],
    accents,
    modes: { dark: mode('dark'), light: mode('light') },
    cvd: null,
    ships: [
      { target: 'css', label: 'CSS custom properties', mode: 'both', path: 'ambergris.css', install: null, files: { both: 'ambergris.css' } },
      { target: 'ghostty', label: 'Ghostty', mode: 'dark', path: 'ports/ghostty/ambergris-dark', install: ['ports/README.md', 'Ghostty — `ghostty/ambergris-dark` (generated)'], files: { dark: 'ports/ghostty/ambergris-dark' } },
      { target: 'zed', label: 'Zed', mode: 'dark', path: 'ports/zed/ambergris.json', install: ['ports/README.md', 'Zed — `zed/ambergris.json` (generated)'], files: { dark: 'ports/zed/ambergris.json' } },
    ],
    also: ['Firefox', 'Mastodon'],
  };
}

export const NEEDS = ['ports/ghostty/ambergris-dark', 'ports/zed/ambergris.json', 'ports/README.md'];
