// Pequod 0.2.0-alpha (pequod.json, commit 619982d). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Pequod.
// Merge into tailwind.config.js, or require() this file and spread it.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "log": {
          "50": "#F7F3EE",
          "100": "#EAE1D7",
          "150": "#DBC9B6",
          "200": "#CFAD8E",
          "300": "#BD8C68",
          "400": "#A16E50",
          "500": "#835A49",
          "600": "#335260",
          "700": "#163F54",
          "800": "#0D2F42",
          "900": "#0C222F",
          "950": "#0B1720"
        },
        "ahab": {
          "DEFAULT": "#E3877C"
        },
        "starbuck": {
          "DEFAULT": "#A6DFFF"
        },
        "queequeg": {
          "DEFAULT": "#838CCF"
        },
        "pip": {
          "DEFAULT": "#DEC577"
        },
        "ishmael": {
          "DEFAULT": "#BFBBB6"
        },
        "stubb": {
          "DEFAULT": "#FFD9BB"
        },
        "tashtego": {
          "DEFAULT": "#82C4A2"
        },
        "daggoo": {
          "DEFAULT": "#A17069"
        },
        "bg": "#0B1720",
        "surface": "#0D2F42",
        "text": "#EAE1D7",
        "text-muted": "#BD8C68",
        "text-subtle": "#A16E50",
        "border": "#163F54",
        "link": "#BD8C68",
        "link-hover": "#BD8C68",
        "accent": "#BD8C68",
        "on-accent": "#0B1720",
        "button": "#BD8C68",
        "on-button": "#0B1720",
        "focus": "#BD8C68",
        "selection": "#0D2F42"
      }
    }
  }
};
