# Ambergris 0.3.0 (tokens.json, commit c92c190). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Ambergris.
# source() this file; needs ggplot2.

ambergris_scale <- c(grey_000 = "#FAFBFD", grey_050 = "#F3F5F7", grey_100 = "#EAEDEF", grey_200 = "#DCDFE3", grey_300 = "#C8CBD0", grey_400 = "#AEB2B7", grey_500 = "#8D9298", grey_600 = "#72777D", grey_700 = "#5C6168", grey_800 = "#42484E", grey_900 = "#2B3037", grey_950 = "#1A1F26", grey_1000 = "#0C1117")

# Dark (dark)
ambergris_dark <- list(
  bg = "#1A1F26", surface = "#0C1117", text = "#EAEDEF", muted = "#AEB2B7",
  grid = "#2B3037", border = "#42484E", accent = "#2F9F99", link = "#5BB6B1"
)
ambergris_accents_dark <- c(accent = "#5BB6B1", sweep_1 = "#13998D", sweep_2 = "#2BA6C6", sweep_3 = "#6FAEF3", sweep_4 = "#A0BAFE", sweep_5 = "#C3CCFE")
ambergris_series_dark <- c("#5BB6B1", "#13998D", "#2BA6C6", "#6FAEF3", "#A0BAFE", "#C3CCFE")
ambergris_sequential_dark <- c("#13998D", "#2BA6C6", "#6FAEF3", "#A0BAFE", "#C3CCFE")

# Light (light)
ambergris_light <- list(
  bg = "#FAFBFD", surface = "#EAEDEF", text = "#1A1F26", muted = "#5C6168",
  grid = "#DCDFE3", border = "#C8CBD0", accent = "#2F9F99", link = "#1E807B"
)
ambergris_accents_light <- c(accent = "#1E807B", sweep_1 = "#2EA094", sweep_2 = "#0587A4", sweep_3 = "#236AAF", sweep_4 = "#304BB0", sweep_5 = "#3428AA")
ambergris_series_light <- c("#1E807B", "#2EA094", "#0587A4", "#236AAF", "#304BB0", "#3428AA")
ambergris_sequential_light <- c("#2EA094", "#0587A4", "#236AAF", "#304BB0", "#3428AA")

#' Discrete colour and fill scales
scale_colour_ambergris_d <- function(mode = "dark", ...) {
  values <- get(paste0("ambergris_series_", mode))
  ggplot2::scale_colour_manual(values = unname(values), ...)
}
scale_color_ambergris_d <- scale_colour_ambergris_d
scale_fill_ambergris_d <- function(mode = "dark", ...) {
  values <- get(paste0("ambergris_series_", mode))
  ggplot2::scale_fill_manual(values = unname(values), ...)
}

#' Continuous (sequential) scales
scale_colour_ambergris_c <- function(mode = "dark", ...) {
  ggplot2::scale_colour_gradientn(colours = get(paste0("ambergris_sequential_", mode)), ...)
}
scale_color_ambergris_c <- scale_colour_ambergris_c
scale_fill_ambergris_c <- function(mode = "dark", ...) {
  ggplot2::scale_fill_gradientn(colours = get(paste0("ambergris_sequential_", mode)), ...)
}

#' A theme on the family's plot surface
theme_ambergris <- function(mode = "dark", base_size = 11) {
  m <- get(paste0("ambergris_", mode))
  ggplot2::theme_minimal(base_size = base_size) +
    ggplot2::theme(
      plot.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      panel.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      panel.grid.major = ggplot2::element_line(colour = m$grid),
      panel.grid.minor = ggplot2::element_blank(),
      text = ggplot2::element_text(colour = m$text),
      axis.text = ggplot2::element_text(colour = m$muted),
      legend.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      strip.text = ggplot2::element_text(colour = m$text)
    )
}
