// Shared plumbing for the generators: a flat, mode-resolved view of a
// family that every format reads, plus naming and header helpers. The
// same code runs at build time (tests, official-versus-generated table)
// and in the browser (the Carpenter).
import { hexToRgb } from '../colour/hex.js';

export const SITE = 'https://gam.tiagojacinto.eu';

/** kebab-case name for a token id: 'log.50' -> 'log-50', 'saxum.pix' -> 'saxum-pix'. */
export const kebab = (id) => String(id).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/** CamelCase for LaTeX and similar: 'log.50' -> 'Log50'. */
export const camel = (id) => String(id).split(/[^a-zA-Z0-9]+/).filter(Boolean).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');

/** snake_case for R and Python: 'log.50' -> 'log_50'. */
export const snake = (id) => kebab(id).replace(/-/g, '_');

export const SYNTAX_ROLES = [
  'keyword', 'string', 'number', 'comment', 'function', 'type', 'constant',
  'variable', 'operator', 'punctuation', 'decorator', 'parameter',
];
export const ROLE_NAMES = [
  'bg', 'surface', 'text', 'textMuted', 'textSubtle', 'border', 'link', 'linkHover',
  'accent', 'onAccent', 'button', 'onButton', 'focus', 'selection',
];
export const ANSI_NAMES = [
  'black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white',
  'bright-black', 'bright-red', 'bright-green', 'bright-yellow', 'bright-blue',
  'bright-magenta', 'bright-cyan', 'bright-white',
];

/**
 * options: { mode: 'dark' | 'light', prefix, accents: [accent ids in order] | null }
 * Returns a plain object with hex strings only.
 */
export function view(fam, options = {}) {
  const mode = options.mode || 'dark';
  const m = fam.modes[mode];
  const chosen = options.accents && options.accents.length
    ? options.accents.map((id) => fam.accents.find((a) => a.id === id)).filter(Boolean)
    : fam.accents;
  const roles = {};
  for (const r of ROLE_NAMES) roles[r] = m.roles[r].hex;
  const syntax = {};
  for (const r of SYNTAX_ROLES) syntax[r] = { hex: m.syntax[r].hex, style: m.syntax[r].style || null };
  const t = m.terminal;
  return {
    id: fam.id,
    name: fam.name,
    version: fam.version,
    commit: fam.source.commit,
    tokenFile: fam.tokenFile,
    repo: fam.repo,
    mode,
    modeLabel: m.label,
    scheme: m.scheme,
    prefix: options.prefix || defaultPrefix(fam.id),
    scaleName: fam.scale.name,
    scale: fam.scale.steps.map((s) => ({ id: s.id, name: kebab(s.id), label: s.label, hex: s.hex })),
    extraScales: (fam.extraScales || []).map((sc) => ({ name: sc.name, steps: sc.steps.map((s) => ({ id: s.id, name: kebab(s.id), label: s.label, hex: s.hex })) })),
    accents: chosen.map((a) => ({ id: a.id, name: kebab(a.id), label: a.label, hue: a.hue, tier: a.tier, hex: a[mode].hex, dark: a.dark.hex, light: a.light.hex })),
    allAccents: fam.accents.map((a) => ({ id: a.id, name: kebab(a.id), label: a.label, hue: a.hue, tier: a.tier, hex: a[mode].hex, dark: a.dark.hex, light: a.light.hex })),
    roles,
    roleRefs: Object.fromEntries(ROLE_NAMES.map((r) => [r, m.roles[r].alias || null])),
    syntax,
    terminal: {
      origin: t.origin,
      bg: t.bg.hex, fg: t.fg.hex, cursor: t.cursor.hex, cursorText: t.cursorText.hex,
      selectionBg: t.selectionBg.hex, selectionFg: t.selectionFg.hex,
      ansi: t.ansi.map((x) => x.hex),
    },
    dataviz: {
      categorical: (m.dataviz.categorical.length ? m.dataviz.categorical : chosen.map((a) => a[mode])).map((x) => x.hex),
      categoricalFromAccents: m.dataviz.categorical.length === 0,
      sequential: m.dataviz.sequential.map((x) => x.hex),
      diverging: m.dataviz.diverging ? m.dataviz.diverging.map((x) => x.hex) : null,
      plot: { bg: m.dataviz.plot.bg.hex, grid: m.dataviz.plot.grid.hex, text: m.dataviz.plot.text.hex, muted: m.dataviz.plot.muted.hex },
    },
  };
}

export function defaultPrefix(id) {
  return { pequod: 'pq', glauca: 'gl', 'try-works': 'tw', ambergris: 'am' }[id] || kebab(id);
}

/** Provenance line every text export carries. */
export function provenance(v) {
  return `${v.name} ${v.version} (${v.tokenFile}, commit ${v.commit}). Generated by Gam, ${SITE}. Tokens CC BY 4.0, attribute ${v.name}.`;
}

/** Wrap the provenance in the comment syntax of a format. */
export function header(v, style, extra = '') {
  const lines = [provenance(v), ...(extra ? [extra] : [])];
  switch (style) {
    case 'css': return `/* ${lines.join('\n   ')} */\n`;
    case 'hash': return lines.map((l) => `# ${l}`).join('\n') + '\n';
    case 'slashes': return lines.map((l) => `// ${l}`).join('\n') + '\n';
    case 'lua': return lines.map((l) => `-- ${l}`).join('\n') + '\n';
    case 'percent': return lines.map((l) => `% ${l}`).join('\n') + '\n';
    case 'xml': return `<!-- ${lines.join(' ')} -->\n`;
    default: return lines.join('\n') + '\n';
  }
}

export const rgb01 = (hex) => hexToRgb(hex).map((c) => c / 255);
export const rgb255 = (hex) => hexToRgb(hex);

/** JSON with two-space indent and a trailing newline. */
export const json = (o) => JSON.stringify(o, null, 2) + '\n';

/** Pretty label for the mode in a file name: 'Pequod-dark'. */
export const fileBase = (v) => `${kebab(v.name)}-${v.mode}`;

/** The set of modes a request covers. */
export const modesOf = (mode) => (mode === 'both' ? ['dark', 'light'] : [mode]);
