# Glauca 0.1.0 (src/glauca.json, commit 1efbcce). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Glauca.
# source() this file; needs ggplot2.

glauca_scale <- c(pruina_charta = "#F0F4F6", pruina_pruina = "#E8EEF2", glaucum_nebula = "#93B7C9", pruina_cinis = "#8C8C8C", glaucum_spuma = "#4D7391", glaucum_vadum = "#2B4356", saxum_petra = "#1F2932", glaucum_caligo = "#142430", saxum_umbra = "#171F26", saxum_pix = "#10161C", saxum_ferrum = "#0B1218")

# Profundum (dark)
glauca_dark <- list(
  bg = "#10161C", surface = "#171F26", text = "#E8EEF2", muted = "#8C8C8C",
  grid = "#2A3540", border = "#2A3540", accent = "#3D97FF", link = "#3D97FF"
)
glauca_accents_dark <- c(dies = "#007AFF", aer = "#6CB2FF", imum = "#084B96", folium = "#62BA46", bacca = "#C96A6A", viola = "#B184DB", lacus = "#4A9EDB", unda = "#45A3AD")
glauca_series_dark <- c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "#D55E00", "#56B4E9", "#F0E442")
glauca_sequential_dark <- c("#EAF2FC", "#C3DCF5", "#92C0EA", "#5B9EDB", "#2F7CC4", "#0B5AA0", "#063A6B")
glauca_diverging_dark <- c("#084B96", "#3672B4", "#7BA1CD", "#C0D3E6", "#F0EFE9", "#E6CDB0", "#D3A26E", "#B97435", "#8F4F16")

# Pruina (light)
glauca_light <- list(
  bg = "#F0F4F6", surface = "#F7FAFB", text = "#16222A", muted = "#55646D",
  grid = "#DDE6EA", border = "#CDD7DC", accent = "#0B62CF", link = "#0B62CF"
)
glauca_accents_light <- c(dies = "#0B62CF", aer = "#084B96", imum = "#084B96", folium = "#3C6E38", bacca = "#784A4D", viola = "#6B588B", lacus = "#33668B", unda = "#306972")
glauca_series_light <- c("#E69F00", "#0072B2", "#009E73", "#CC79A7", "#D55E00", "#56B4E9", "#F0E442")
glauca_sequential_light <- c("#EAF2FC", "#C3DCF5", "#92C0EA", "#5B9EDB", "#2F7CC4", "#0B5AA0", "#063A6B")
glauca_diverging_light <- c("#084B96", "#3672B4", "#7BA1CD", "#C0D3E6", "#F0EFE9", "#E6CDB0", "#D3A26E", "#B97435", "#8F4F16")

#' Discrete colour and fill scales
scale_colour_glauca_d <- function(mode = "dark", ...) {
  values <- get(paste0("glauca_series_", mode))
  ggplot2::scale_colour_manual(values = unname(values), ...)
}
scale_color_glauca_d <- scale_colour_glauca_d
scale_fill_glauca_d <- function(mode = "dark", ...) {
  values <- get(paste0("glauca_series_", mode))
  ggplot2::scale_fill_manual(values = unname(values), ...)
}

#' Continuous (sequential) scales
scale_colour_glauca_c <- function(mode = "dark", ...) {
  ggplot2::scale_colour_gradientn(colours = get(paste0("glauca_sequential_", mode)), ...)
}
scale_color_glauca_c <- scale_colour_glauca_c
scale_fill_glauca_c <- function(mode = "dark", ...) {
  ggplot2::scale_fill_gradientn(colours = get(paste0("glauca_sequential_", mode)), ...)
}

#' Diverging scales
scale_colour_glauca_div <- function(mode = "dark", ...) {
  ggplot2::scale_colour_gradientn(colours = get(paste0("glauca_diverging_", mode)), ...)
}
scale_fill_glauca_div <- function(mode = "dark", ...) {
  ggplot2::scale_fill_gradientn(colours = get(paste0("glauca_diverging_", mode)), ...)
}

#' A theme on the family's plot surface
theme_glauca <- function(mode = "dark", base_size = 11) {
  m <- get(paste0("glauca_", mode))
  ggplot2::theme_minimal(base_size = base_size) +
    ggplot2::theme(
      plot.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      panel.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      panel.grid.major = ggplot2::element_line(colour = m$grid),
      panel.grid.minor = ggplot2::element_blank(),
      text = ggplot2::element_text(colour = m$text),
      axis.text = ggplot2::element_text(colour = m$muted),
      legend.background = ggplot2::element_rect(fill = m$bg, colour = NA),
      strip.text = ggplot2::element_text(colour = m$text)
    )
}
