// Pequod 0.2.0-alpha (pequod.json, commit 619982d). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Pequod.
// Merge into tailwind.config.js, or require() this file and spread it.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "log": {
          "50": "#F7F3EE",
          "100": "#EAE1D7",
          "150": "#DBC9B6",
          "200": "#CFAD8E",
          "300": "#BD8C68",
          "400": "#A16E50",
          "500": "#835A49",
          "600": "#335260",
          "700": "#163F54",
          "800": "#0D2F42",
          "900": "#0C222F",
          "950": "#0B1720"
        },
        "ahab": {
          "DEFAULT": "#A83732",
          "light": "#A83732",
          "dark": "#E3877C"
        },
        "starbuck": {
          "DEFAULT": "#0082B1",
          "light": "#0082B1",
          "dark": "#A6DFFF"
        },
        "queequeg": {
          "DEFAULT": "#253E82",
          "light": "#253E82",
          "dark": "#838CCF"
        },
        "pip": {
          "DEFAULT": "#6A4A00",
          "light": "#6A4A00",
          "dark": "#DEC577"
        },
        "ishmael": {
          "DEFAULT": "#76716B",
          "light": "#76716B",
          "dark": "#BFBBB6"
        },
        "stubb": {
          "DEFAULT": "#CA6435",
          "light": "#CA6435",
          "dark": "#FFD9BB"
        },
        "tashtego": {
          "DEFAULT": "#177C55",
          "light": "#177C55",
          "dark": "#82C4A2"
        },
        "daggoo": {
          "DEFAULT": "#552823",
          "light": "#552823",
          "dark": "#A17069"
        },
        "light": {
          "bg": "#EAE1D7",
          "surface": "#DBC9B6",
          "text": "#0D2F42",
          "text-muted": "#335260",
          "text-subtle": "#835A49",
          "border": "#CFAD8E",
          "link": "#163F54",
          "link-hover": "#163F54",
          "accent": "#163F54",
          "on-accent": "#EAE1D7",
          "button": "#163F54",
          "on-button": "#EAE1D7",
          "focus": "#A16E50",
          "selection": "#DBC9B6"
        },
        "dark": {
          "bg": "#0B1720",
          "surface": "#0D2F42",
          "text": "#EAE1D7",
          "text-muted": "#BD8C68",
          "text-subtle": "#A16E50",
          "border": "#163F54",
          "link": "#BD8C68",
          "link-hover": "#BD8C68",
          "accent": "#BD8C68",
          "on-accent": "#0B1720",
          "button": "#BD8C68",
          "on-button": "#0B1720",
          "focus": "#BD8C68",
          "selection": "#0D2F42"
        }
      }
    }
  }
};
