-- Glauca 0.1.0 (src/glauca.json, commit 1efbcce). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Glauca.
-- Save as ~/.config/wezterm/colors/glauca-dark.lua; then: config.color_scheme = "Glauca Profundum"
return {
  foreground = "#E8EEF2",
  background = "#10161C",
  cursor_bg = "#007AFF",
  cursor_fg = "#0B1218",
  cursor_border = "#007AFF",
  selection_bg = "#2B4356",
  selection_fg = "#E8EEF2",
  split = "#2A3540",
  ansi = { "#171F26", "#B85F5F", "#4F9E3F", "#C79A3D", "#4981C4", "#8E74AB", "#3F93A0", "#C6CED4" },
  brights = { "#3A4754", "#C96A6A", "#62BA46", "#D9AE4A", "#007AFF", "#B184DB", "#7FC4CF", "#E8EEF2" },
  tab_bar = {
    background = "#171F26",
    active_tab = { bg_color = "#10161C", fg_color = "#E8EEF2" },
    inactive_tab = { bg_color = "#171F26", fg_color = "#8C8C8C" },
    inactive_tab_hover = { bg_color = "#2B4356", fg_color = "#E8EEF2" },
    new_tab = { bg_color = "#171F26", fg_color = "#8C8C8C" },
  },
}
