-- Glauca 0.1.0 (src/glauca.json, commit 1efbcce). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Glauca.
-- Save as ~/.config/wezterm/colors/glauca-light.lua; then: config.color_scheme = "Glauca Pruina"
return {
  foreground = "#16222A",
  background = "#F0F4F6",
  cursor_bg = "#0B62CF",
  cursor_fg = "#F2F7FB",
  cursor_border = "#0B62CF",
  selection_bg = "#35576B",
  selection_fg = "#F2F7FB",
  split = "#CDD7DC",
  ansi = { "#0B1218", "#A55859", "#3F7B39", "#846C36", "#4070A8", "#786594", "#357884", "#3E4D55" },
  brights = { "#55646D", "#B06061", "#47833C", "#87733D", "#0273EE", "#8669A9", "#517D86", "#16222A" },
  tab_bar = {
    background = "#F7FAFB",
    active_tab = { bg_color = "#F0F4F6", fg_color = "#16222A" },
    inactive_tab = { bg_color = "#F7FAFB", fg_color = "#55646D" },
    inactive_tab_hover = { bg_color = "#B7CDD6", fg_color = "#16222A" },
    new_tab = { bg_color = "#F7FAFB", fg_color = "#55646D" },
  },
}
