// Glauca 0.1.0 (src/glauca.json, commit 1efbcce). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Glauca.
// Plot.plot({color: {range: glaucaDark}}) or d3.scaleOrdinal(glaucaDark).
export const glaucaScale = ["#F0F4F6","#E8EEF2","#93B7C9","#8C8C8C","#4D7391","#2B4356","#1F2932","#142430","#171F26","#10161C","#0B1218"];
export const glaucaDark = ["#E69F00","#0072B2","#009E73","#CC79A7","#D55E00","#56B4E9","#F0E442"];
export const glaucaSequentialDark = ["#EAF2FC","#C3DCF5","#92C0EA","#5B9EDB","#2F7CC4","#0B5AA0","#063A6B"];
export const glaucaDivergingDark = ["#084B96","#3672B4","#7BA1CD","#C0D3E6","#F0EFE9","#E6CDB0","#D3A26E","#B97435","#8F4F16"];
export const glaucaPlotDark = {"bg":"#10161C","grid":"#2A3540","text":"#E8EEF2","muted":"#8C8C8C"};
export const glaucaLight = ["#E69F00","#0072B2","#009E73","#CC79A7","#D55E00","#56B4E9","#F0E442"];
export const glaucaSequentialLight = ["#EAF2FC","#C3DCF5","#92C0EA","#5B9EDB","#2F7CC4","#0B5AA0","#063A6B"];
export const glaucaDivergingLight = ["#084B96","#3672B4","#7BA1CD","#C0D3E6","#F0EFE9","#E6CDB0","#D3A26E","#B97435","#8F4F16"];
export const glaucaPlotLight = {"bg":"#FFFFFF","grid":"#DDE6EA","text":"#16222A","muted":"#55646D"};
export default glaucaDark;
