-- Try-Works 1.0.0 (src/try-works.json, commit 400dd91). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Try-Works.
-- Save as ~/.config/wezterm/colors/try-works-dark.lua; then: config.color_scheme = "Try-Works Try-Fire"
return {
  foreground = "#F1EFE9",
  background = "#12161B",
  cursor_bg = "#C9651D",
  cursor_fg = "#11151A",
  cursor_border = "#C9651D",
  selection_bg = "#2C4953",
  selection_fg = "#F1EFE9",
  split = "#2C3640",
  ansi = { "#1B2127", "#C05A3A", "#6F8F6A", "#C9651D", "#46708A", "#8A6F9E", "#5F97A0", "#C9CCCE" },
  brights = { "#3A4754", "#D06A52", "#86A87F", "#E0832A", "#5F93B0", "#A487BA", "#8FB6BD", "#F1EFE9" },
  tab_bar = {
    background = "#1B2127",
    active_tab = { bg_color = "#12161B", fg_color = "#F1EFE9" },
    inactive_tab = { bg_color = "#1B2127", fg_color = "#97A0A4" },
    inactive_tab_hover = { bg_color = "#2C4953", fg_color = "#F1EFE9" },
    new_tab = { bg_color = "#1B2127", fg_color = "#97A0A4" },
  },
}
