-- Try-Works 1.0.0 (src/try-works.json, commit 400dd91). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Try-Works.
-- Save as ~/.config/wezterm/colors/try-works-light.lua; then: config.color_scheme = "Try-Works True Lamp"
return {
  foreground = "#18272B",
  background = "#DEE7E4",
  cursor_bg = "#9E5017",
  cursor_fg = "#EEF3F0",
  cursor_border = "#9E5017",
  selection_bg = "#264852",
  selection_fg = "#EEF3F0",
  split = "#C4D2CD",
  ansi = { "#1B2127", "#C05A3A", "#6F8F6A", "#C9651D", "#46708A", "#8A6F9E", "#5F97A0", "#C9CCCE" },
  brights = { "#3A4754", "#D06A52", "#86A87F", "#E0832A", "#5F93B0", "#A487BA", "#8FB6BD", "#F1EFE9" },
  tab_bar = {
    background = "#E7EFEB",
    active_tab = { bg_color = "#DEE7E4", fg_color = "#18272B" },
    inactive_tab = { bg_color = "#E7EFEB", fg_color = "#52646A" },
    inactive_tab_hover = { bg_color = "#B4CCC9", fg_color = "#18272B" },
    new_tab = { bg_color = "#E7EFEB", fg_color = "#52646A" },
  },
}
