-- Pequod 0.2.0-alpha (pequod.json, commit 619982d). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Pequod.
-- Save as ~/.config/wezterm/colors/pequod-dark.lua; then: config.color_scheme = "Pequod Below deck"
return {
  foreground = "#EAE1D7",
  background = "#0B1720",
  cursor_bg = "#BD8C68",
  cursor_fg = "#0B1720",
  cursor_border = "#BD8C68",
  selection_bg = "#0D2F42",
  selection_fg = "#EAE1D7",
  split = "#163F54",
  ansi = { "#0C222F", "#E3877C", "#82C4A2", "#DEC577", "#A6DFFF", "#838CCF", "#9DC2C5", "#EAE1D7" },
  brights = { "#335260", "#E99C93", "#AFCCA6", "#E8CB8C", "#A0C2D4", "#AAADDA", "#BCD9DB", "#F7F3EE" },
  tab_bar = {
    background = "#0D2F42",
    active_tab = { bg_color = "#0B1720", fg_color = "#EAE1D7" },
    inactive_tab = { bg_color = "#0D2F42", fg_color = "#BD8C68" },
    inactive_tab_hover = { bg_color = "#0D2F42", fg_color = "#EAE1D7" },
    new_tab = { bg_color = "#0D2F42", fg_color = "#BD8C68" },
  },
}
