// Pequod 0.2.0-alpha (pequod.json, commit 619982d). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Pequod.
// Plot.plot({color: {range: pequodDark}}) or d3.scaleOrdinal(pequodDark).
export const pequodScale = ["#F7F3EE","#EAE1D7","#DBC9B6","#CFAD8E","#BD8C68","#A16E50","#835A49","#335260","#163F54","#0D2F42","#0C222F","#0B1720"];
export const pequodDark = ["#E3877C","#A6DFFF","#838CCF","#DEC577","#BFBBB6","#FFD9BB","#82C4A2","#A17069"];
export const pequodSequentialDark = ["#F7F3EE","#EAE1D7","#DBC9B6","#CFAD8E","#BD8C68","#A16E50","#835A49","#335260","#163F54","#0D2F42","#0C222F","#0B1720"];
export const pequodPlotDark = {"bg":"#0B1720","grid":"#163F54","text":"#EAE1D7","muted":"#BD8C68"};
export default pequodDark;
