-- Pequod 0.2.0-alpha (pequod.json, commit 619982d). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Pequod.
-- Copy to ~/.config/nvim/colors/pequod-light.lua and :colorscheme pequod-light

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "light"
vim.g.colors_name = "pequod-light"

local function hi(group, spec) vim.api.nvim_set_hl(0, group, spec) end

  hi("Normal", { fg = "#0D2F42", bg = "#EAE1D7" })
  hi("NormalFloat", { fg = "#0D2F42", bg = "#DBC9B6" })
  hi("NormalNC", { fg = "#0D2F42", bg = "#EAE1D7" })
  hi("Comment", { fg = "#76716B", italic = true })
  hi("String", { fg = "#177C55" })
  hi("Character", { fg = "#177C55" })
  hi("Number", { fg = "#6A4A00" })
  hi("Float", { fg = "#6A4A00" })
  hi("Boolean", { fg = "#6A4A00" })
  hi("Constant", { fg = "#CA6435" })
  hi("Identifier", { fg = "#552823" })
  hi("Function", { fg = "#0082B1" })
  hi("Statement", { fg = "#A83732" })
  hi("Keyword", { fg = "#A83732" })
  hi("Conditional", { fg = "#A83732" })
  hi("Repeat", { fg = "#A83732" })
  hi("Operator", { fg = "#76716B" })
  hi("Exception", { fg = "#A83732" })
  hi("PreProc", { fg = "#CA6435" })
  hi("Include", { fg = "#A83732" })
  hi("Define", { fg = "#CA6435" })
  hi("Macro", { fg = "#CA6435" })
  hi("Type", { fg = "#253E82" })
  hi("StorageClass", { fg = "#A83732" })
  hi("Structure", { fg = "#253E82" })
  hi("Typedef", { fg = "#253E82" })
  hi("Special", { fg = "#CA6435" })
  hi("Delimiter", { fg = "#76716B" })
  hi("Todo", { fg = "#EAE1D7", bg = "#163F54", bold = true })
  hi("Underlined", { fg = "#163F54", underline = true })
  hi("Error", { fg = "#A83732" })
  hi("Title", { fg = "#A83732", bold = true })
  hi("LineNr", { fg = "#835A49", bg = "#EAE1D7" })
  hi("CursorLineNr", { fg = "#0D2F42", bold = true })
  hi("CursorLine", { bg = "#DBC9B6" })
  hi("ColorColumn", { bg = "#DBC9B6" })
  hi("SignColumn", { bg = "#EAE1D7" })
  hi("VertSplit", { fg = "#CFAD8E" })
  hi("WinSeparator", { fg = "#CFAD8E" })
  hi("Visual", { bg = "#DBC9B6" })
  hi("Search", { fg = "#EAE1D7", bg = "#163F54" })
  hi("IncSearch", { fg = "#EAE1D7", bg = "#163F54" })
  hi("CurSearch", { fg = "#EAE1D7", bg = "#163F54" })
  hi("MatchParen", { fg = "#163F54", bold = true, underline = true })
  hi("Pmenu", { fg = "#0D2F42", bg = "#DBC9B6" })
  hi("PmenuSel", { fg = "#0D2F42", bg = "#DBC9B6" })
  hi("PmenuSbar", { bg = "#DBC9B6" })
  hi("PmenuThumb", { bg = "#835A49" })
  hi("StatusLine", { fg = "#0D2F42", bg = "#DBC9B6" })
  hi("StatusLineNC", { fg = "#335260", bg = "#DBC9B6" })
  hi("TabLine", { fg = "#335260", bg = "#DBC9B6" })
  hi("TabLineSel", { fg = "#0D2F42", bg = "#EAE1D7", bold = true })
  hi("TabLineFill", { bg = "#DBC9B6" })
  hi("NonText", { fg = "#CFAD8E" })
  hi("Whitespace", { fg = "#CFAD8E" })
  hi("EndOfBuffer", { fg = "#EAE1D7" })
  hi("Directory", { fg = "#163F54" })
  hi("Question", { fg = "#177C55" })
  hi("MoreMsg", { fg = "#177C55" })
  hi("ErrorMsg", { fg = "#A83732" })
  hi("WarningMsg", { fg = "#6A4A00" })
  hi("FloatBorder", { fg = "#CFAD8E", bg = "#DBC9B6" })
  hi("Cursor", { fg = "#EAE1D7", bg = "#163F54" })
  hi("DiffAdd", { bg = "#177C55" })
  hi("DiffDelete", { fg = "#A83732" })
  hi("DiffChange", { bg = "#DBC9B6" })
  hi("DiffText", { bg = "#DBC9B6" })
  hi("DiagnosticError", { fg = "#A83732" })
  hi("DiagnosticWarn", { fg = "#6A4A00" })
  hi("DiagnosticInfo", { fg = "#0082B1" })
  hi("DiagnosticHint", { fg = "#335260" })
  hi("@comment", { link = "Comment" })
  hi("@string", { link = "String" })
  hi("@number", { link = "Number" })
  hi("@keyword", { link = "Keyword" })
  hi("@function", { link = "Function" })
  hi("@function.call", { link = "Function" })
  hi("@type", { link = "Type" })
  hi("@constant", { link = "Constant" })
  hi("@variable", { fg = "#552823" })
  hi("@variable.parameter", { fg = "#552823" })
  hi("@operator", { link = "Operator" })
  hi("@punctuation", { link = "Delimiter" })
  hi("@attribute", { fg = "#CA6435" })
  hi("@property", { fg = "#552823" })
  hi("@tag", { fg = "#A83732" })
  hi("@markup.heading", { fg = "#A83732", bold = true })
  hi("@markup.link.url", { fg = "#163F54", underline = true })
  hi("@markup.raw", { fg = "#177C55" })

vim.g.terminal_color_0 = "#0C222F"
vim.g.terminal_color_1 = "#A83732"
vim.g.terminal_color_2 = "#177C55"
vim.g.terminal_color_3 = "#6A4A00"
vim.g.terminal_color_4 = "#0082B1"
vim.g.terminal_color_5 = "#253E82"
vim.g.terminal_color_6 = "#0C7F83"
vim.g.terminal_color_7 = "#835A49"
vim.g.terminal_color_8 = "#335260"
vim.g.terminal_color_9 = "#893535"
vim.g.terminal_color_10 = "#156D51"
vim.g.terminal_color_11 = "#57450D"
vim.g.terminal_color_12 = "#03719B"
vim.g.terminal_color_13 = "#203B75"
vim.g.terminal_color_14 = "#0C6F76"
vim.g.terminal_color_15 = "#0D2F42"
