// Try-Works 1.0.0 (src/try-works.json, commit 400dd91). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Try-Works.
// Merge into tailwind.config.js, or require() this file and spread it.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "sea": {
          "whale": "#F1EFE9",
          "bone": "#DEE7E4",
          "foam": "#8FB6BD",
          "gull": "#97A0A4",
          "spray": "#4D7680",
          "swell": "#2C4953",
          "deck": "#232B32",
          "trough": "#14242C",
          "hold": "#1B2127",
          "pitch": "#12161B",
          "iron": "#11151A"
        },
        "ember": {
          "DEFAULT": "#9E5017",
          "light": "#9E5017",
          "dark": "#C9651D"
        },
        "flame": {
          "DEFAULT": "#7A3A10",
          "light": "#7A3A10",
          "dark": "#E0832A"
        },
        "oil": {
          "DEFAULT": "#7A3A10",
          "light": "#7A3A10",
          "dark": "#9A4A16"
        },
        "kelp": {
          "DEFAULT": "#4F6855",
          "light": "#4F6855",
          "dark": "#86A87F"
        },
        "brick": {
          "DEFAULT": "#7D4C40",
          "light": "#7D4C40",
          "dark": "#D06A52"
        },
        "dusk": {
          "DEFAULT": "#655C7A",
          "light": "#655C7A",
          "dark": "#A487BA"
        },
        "tide": {
          "DEFAULT": "#3F6274",
          "light": "#3F6274",
          "dark": "#5F93B0"
        },
        "shoal": {
          "DEFAULT": "#3F656B",
          "light": "#3F656B",
          "dark": "#5F97A0"
        },
        "light": {
          "bg": "#DEE7E4",
          "surface": "#E7EFEB",
          "text": "#18272B",
          "text-muted": "#52646A",
          "text-subtle": "#52646A",
          "border": "#C4D2CD",
          "link": "#9E5017",
          "link-hover": "#7A3A10",
          "accent": "#9E5017",
          "on-accent": "#EEF3F0",
          "button": "#9E5017",
          "on-button": "#EEF3F0",
          "focus": "#9E5017",
          "selection": "#B4CCC9"
        },
        "dark": {
          "bg": "#12161B",
          "surface": "#1B2127",
          "text": "#F1EFE9",
          "text-muted": "#97A0A4",
          "text-subtle": "#97A0A4",
          "border": "#2C3640",
          "link": "#C9651D",
          "link-hover": "#E0832A",
          "accent": "#C9651D",
          "on-accent": "#11151A",
          "button": "#C9651D",
          "on-button": "#11151A",
          "focus": "#E0832A",
          "selection": "#2C4953"
        }
      }
    }
  }
};
