-- Ambergris 0.3.0 (tokens.json, commit c92c190). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Ambergris.
-- Save as ~/.config/wezterm/colors/ambergris-dark.lua; then: config.color_scheme = "Ambergris Dark"
return {
  foreground = "#EAEDEF",
  background = "#0C1117",
  cursor_bg = "#FAFBFD",
  cursor_fg = "#0C1117",
  cursor_border = "#FAFBFD",
  selection_bg = "#143336",
  selection_fg = "#FAFBFD",
  split = "#42484E",
  ansi = { "#1A1F26", "#CF7F79", "#7BB587", "#D4BC79", "#72A5DE", "#B893D4", "#5BB6B1", "#C8CBD0" },
  brights = { "#5C6168", "#E7958E", "#91CB9C", "#E8CF8C", "#88BCF6", "#CEA9EB", "#86CDC8", "#FAFBFD" },
  tab_bar = {
    background = "#0C1117",
    active_tab = { bg_color = "#1A1F26", fg_color = "#EAEDEF" },
    inactive_tab = { bg_color = "#0C1117", fg_color = "#AEB2B7" },
    inactive_tab_hover = { bg_color = "#0E3937", fg_color = "#EAEDEF" },
    new_tab = { bg_color = "#0C1117", fg_color = "#AEB2B7" },
  },
}
