-- Ambergris 0.3.0 (tokens.json, commit c92c190). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Ambergris.
-- Save as ~/.config/wezterm/colors/ambergris-light.lua; then: config.color_scheme = "Ambergris Light"
return {
  foreground = "#1A1F26",
  background = "#FAFBFD",
  cursor_bg = "#0C1117",
  cursor_fg = "#FAFBFD",
  cursor_border = "#0C1117",
  selection_bg = "#C9E5E5",
  selection_fg = "#1A1F26",
  split = "#C8CBD0",
  ansi = { "#1A1F26", "#CF7F79", "#7BB587", "#D4BC79", "#72A5DE", "#B893D4", "#5BB6B1", "#C8CBD0" },
  brights = { "#5C6168", "#E7958E", "#91CB9C", "#E8CF8C", "#88BCF6", "#CEA9EB", "#86CDC8", "#FAFBFD" },
  tab_bar = {
    background = "#EAEDEF",
    active_tab = { bg_color = "#FAFBFD", fg_color = "#1A1F26" },
    inactive_tab = { bg_color = "#EAEDEF", fg_color = "#5C6168" },
    inactive_tab_hover = { bg_color = "#E7F8F6", fg_color = "#1A1F26" },
    new_tab = { bg_color = "#EAEDEF", fg_color = "#5C6168" },
  },
}
