# Pequod 0.2.0-alpha (pequod.json, commit 619982d). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Pequod.
# import this module and call register_cmaps() once.
from matplotlib.colors import LinearSegmentedColormap
import matplotlib as mpl

SCALE = {"log_50": "#F7F3EE", "log_100": "#EAE1D7", "log_150": "#DBC9B6", "log_200": "#CFAD8E", "log_300": "#BD8C68", "log_400": "#A16E50", "log_500": "#835A49", "log_600": "#335260", "log_700": "#163F54", "log_800": "#0D2F42", "log_900": "#0C222F", "log_950": "#0B1720"}
ACCENTS_DARK = {"ahab": "#E3877C", "starbuck": "#A6DFFF", "queequeg": "#838CCF", "pip": "#DEC577", "ishmael": "#BFBBB6", "stubb": "#FFD9BB", "tashtego": "#82C4A2", "daggoo": "#A17069"}
SERIES_DARK = ["#E3877C", "#A6DFFF", "#838CCF", "#DEC577", "#BFBBB6", "#FFD9BB", "#82C4A2", "#A17069"]
SEQUENTIAL_DARK = ["#F7F3EE", "#EAE1D7", "#DBC9B6", "#CFAD8E", "#BD8C68", "#A16E50", "#835A49", "#335260", "#163F54", "#0D2F42", "#0C222F", "#0B1720"]


def register_cmaps():
    """Register pequod_seq_<mode> (and _div where the family has one)."""
    mpl.colormaps.register(LinearSegmentedColormap.from_list("pequod_seq_dark", SEQUENTIAL_DARK), force=True)


def use(mode="dark"):
    """Apply the series cycle for a mode."""
    mpl.rcParams["axes.prop_cycle"] = mpl.cycler(color=globals()["SERIES_" + mode.upper()])
