-- Try-Works 1.0.0 (src/try-works.json, commit 400dd91). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Try-Works.
-- Copy to ~/.config/nvim/colors/try-works-dark.lua and :colorscheme try-works-dark

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "try-works-dark"

local function hi(group, spec) vim.api.nvim_set_hl(0, group, spec) end

  hi("Normal", { fg = "#F1EFE9", bg = "#12161B" })
  hi("NormalFloat", { fg = "#F1EFE9", bg = "#1B2127" })
  hi("NormalNC", { fg = "#F1EFE9", bg = "#12161B" })
  hi("Comment", { fg = "#97A0A4", italic = true })
  hi("String", { fg = "#86A87F" })
  hi("Character", { fg = "#86A87F" })
  hi("Number", { fg = "#A487BA" })
  hi("Float", { fg = "#A487BA" })
  hi("Boolean", { fg = "#A487BA" })
  hi("Constant", { fg = "#A487BA" })
  hi("Identifier", { fg = "#F1EFE9" })
  hi("Function", { fg = "#5F93B0" })
  hi("Statement", { fg = "#C9651D", bold = true })
  hi("Keyword", { fg = "#C9651D", bold = true })
  hi("Conditional", { fg = "#C9651D", bold = true })
  hi("Repeat", { fg = "#C9651D", bold = true })
  hi("Operator", { fg = "#AEB6B8" })
  hi("Exception", { fg = "#C9651D", bold = true })
  hi("PreProc", { fg = "#D06A52" })
  hi("Include", { fg = "#C9651D", bold = true })
  hi("Define", { fg = "#D06A52" })
  hi("Macro", { fg = "#D06A52" })
  hi("Type", { fg = "#5F97A0", italic = true })
  hi("StorageClass", { fg = "#C9651D", bold = true })
  hi("Structure", { fg = "#5F97A0", italic = true })
  hi("Typedef", { fg = "#5F97A0", italic = true })
  hi("Special", { fg = "#A487BA" })
  hi("Delimiter", { fg = "#8A9296" })
  hi("Todo", { fg = "#11151A", bg = "#C9651D", bold = true })
  hi("Underlined", { fg = "#C9651D", underline = true })
  hi("Error", { fg = "#C9651D" })
  hi("Title", { fg = "#C9651D", bold = true })
  hi("LineNr", { fg = "#97A0A4", bg = "#12161B" })
  hi("CursorLineNr", { fg = "#F1EFE9", bold = true })
  hi("CursorLine", { bg = "#1B2127" })
  hi("ColorColumn", { bg = "#1B2127" })
  hi("SignColumn", { bg = "#12161B" })
  hi("VertSplit", { fg = "#2C3640" })
  hi("WinSeparator", { fg = "#2C3640" })
  hi("Visual", { bg = "#2C4953" })
  hi("Search", { fg = "#11151A", bg = "#C9651D" })
  hi("IncSearch", { fg = "#11151A", bg = "#C9651D" })
  hi("CurSearch", { fg = "#11151A", bg = "#C9651D" })
  hi("MatchParen", { fg = "#C9651D", bold = true, underline = true })
  hi("Pmenu", { fg = "#F1EFE9", bg = "#1B2127" })
  hi("PmenuSel", { fg = "#F1EFE9", bg = "#2C4953" })
  hi("PmenuSbar", { bg = "#1B2127" })
  hi("PmenuThumb", { bg = "#97A0A4" })
  hi("StatusLine", { fg = "#F1EFE9", bg = "#1B2127" })
  hi("StatusLineNC", { fg = "#97A0A4", bg = "#1B2127" })
  hi("TabLine", { fg = "#97A0A4", bg = "#1B2127" })
  hi("TabLineSel", { fg = "#F1EFE9", bg = "#12161B", bold = true })
  hi("TabLineFill", { bg = "#1B2127" })
  hi("NonText", { fg = "#2C3640" })
  hi("Whitespace", { fg = "#2C3640" })
  hi("EndOfBuffer", { fg = "#12161B" })
  hi("Directory", { fg = "#C9651D" })
  hi("Question", { fg = "#86A87F" })
  hi("MoreMsg", { fg = "#86A87F" })
  hi("ErrorMsg", { fg = "#C9651D" })
  hi("WarningMsg", { fg = "#A487BA" })
  hi("FloatBorder", { fg = "#2C3640", bg = "#1B2127" })
  hi("Cursor", { fg = "#11151A", bg = "#C9651D" })
  hi("DiffAdd", { bg = "#86A87F" })
  hi("DiffDelete", { fg = "#C9651D" })
  hi("DiffChange", { bg = "#1B2127" })
  hi("DiffText", { bg = "#2C4953" })
  hi("DiagnosticError", { fg = "#C9651D" })
  hi("DiagnosticWarn", { fg = "#A487BA" })
  hi("DiagnosticInfo", { fg = "#5F93B0" })
  hi("DiagnosticHint", { fg = "#97A0A4" })
  hi("@comment", { link = "Comment" })
  hi("@string", { link = "String" })
  hi("@number", { link = "Number" })
  hi("@keyword", { link = "Keyword" })
  hi("@function", { link = "Function" })
  hi("@function.call", { link = "Function" })
  hi("@type", { link = "Type" })
  hi("@constant", { link = "Constant" })
  hi("@variable", { fg = "#F1EFE9" })
  hi("@variable.parameter", { fg = "#CDD2D3" })
  hi("@operator", { link = "Operator" })
  hi("@punctuation", { link = "Delimiter" })
  hi("@attribute", { fg = "#D06A52" })
  hi("@property", { fg = "#F1EFE9" })
  hi("@tag", { fg = "#C9651D", bold = true })
  hi("@markup.heading", { fg = "#C9651D", bold = true })
  hi("@markup.link.url", { fg = "#C9651D", underline = true })
  hi("@markup.raw", { fg = "#86A87F" })

vim.g.terminal_color_0 = "#1B2127"
vim.g.terminal_color_1 = "#C05A3A"
vim.g.terminal_color_2 = "#6F8F6A"
vim.g.terminal_color_3 = "#C9651D"
vim.g.terminal_color_4 = "#46708A"
vim.g.terminal_color_5 = "#8A6F9E"
vim.g.terminal_color_6 = "#5F97A0"
vim.g.terminal_color_7 = "#C9CCCE"
vim.g.terminal_color_8 = "#3A4754"
vim.g.terminal_color_9 = "#D06A52"
vim.g.terminal_color_10 = "#86A87F"
vim.g.terminal_color_11 = "#E0832A"
vim.g.terminal_color_12 = "#5F93B0"
vim.g.terminal_color_13 = "#A487BA"
vim.g.terminal_color_14 = "#8FB6BD"
vim.g.terminal_color_15 = "#F1EFE9"
