-- Try-Works 1.0.0 (src/try-works.json, commit 400dd91). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Try-Works.
-- Copy to ~/.config/nvim/colors/try-works-light.lua and :colorscheme try-works-light

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "light"
vim.g.colors_name = "try-works-light"

local function hi(group, spec) vim.api.nvim_set_hl(0, group, spec) end

  hi("Normal", { fg = "#18272B", bg = "#DEE7E4" })
  hi("NormalFloat", { fg = "#18272B", bg = "#E7EFEB" })
  hi("NormalNC", { fg = "#18272B", bg = "#DEE7E4" })
  hi("Comment", { fg = "#52646A", italic = true })
  hi("String", { fg = "#4F6855" })
  hi("Character", { fg = "#4F6855" })
  hi("Number", { fg = "#655C7A" })
  hi("Float", { fg = "#655C7A" })
  hi("Boolean", { fg = "#655C7A" })
  hi("Constant", { fg = "#655C7A" })
  hi("Identifier", { fg = "#18272B" })
  hi("Function", { fg = "#3F6274" })
  hi("Statement", { fg = "#9E5017", bold = true })
  hi("Keyword", { fg = "#9E5017", bold = true })
  hi("Conditional", { fg = "#9E5017", bold = true })
  hi("Repeat", { fg = "#9E5017", bold = true })
  hi("Operator", { fg = "#52646A" })
  hi("Exception", { fg = "#9E5017", bold = true })
  hi("PreProc", { fg = "#7D4C40" })
  hi("Include", { fg = "#9E5017", bold = true })
  hi("Define", { fg = "#7D4C40" })
  hi("Macro", { fg = "#7D4C40" })
  hi("Type", { fg = "#3F656B", italic = true })
  hi("StorageClass", { fg = "#9E5017", bold = true })
  hi("Structure", { fg = "#3F656B", italic = true })
  hi("Typedef", { fg = "#3F656B", italic = true })
  hi("Special", { fg = "#655C7A" })
  hi("Delimiter", { fg = "#52646A" })
  hi("Todo", { fg = "#EEF3F0", bg = "#9E5017", bold = true })
  hi("Underlined", { fg = "#9E5017", underline = true })
  hi("Error", { fg = "#9E5017" })
  hi("Title", { fg = "#9E5017", bold = true })
  hi("LineNr", { fg = "#52646A", bg = "#DEE7E4" })
  hi("CursorLineNr", { fg = "#18272B", bold = true })
  hi("CursorLine", { bg = "#E7EFEB" })
  hi("ColorColumn", { bg = "#E7EFEB" })
  hi("SignColumn", { bg = "#DEE7E4" })
  hi("VertSplit", { fg = "#C4D2CD" })
  hi("WinSeparator", { fg = "#C4D2CD" })
  hi("Visual", { bg = "#B4CCC9" })
  hi("Search", { fg = "#EEF3F0", bg = "#9E5017" })
  hi("IncSearch", { fg = "#EEF3F0", bg = "#9E5017" })
  hi("CurSearch", { fg = "#EEF3F0", bg = "#9E5017" })
  hi("MatchParen", { fg = "#9E5017", bold = true, underline = true })
  hi("Pmenu", { fg = "#18272B", bg = "#E7EFEB" })
  hi("PmenuSel", { fg = "#18272B", bg = "#B4CCC9" })
  hi("PmenuSbar", { bg = "#E7EFEB" })
  hi("PmenuThumb", { bg = "#52646A" })
  hi("StatusLine", { fg = "#18272B", bg = "#E7EFEB" })
  hi("StatusLineNC", { fg = "#52646A", bg = "#E7EFEB" })
  hi("TabLine", { fg = "#52646A", bg = "#E7EFEB" })
  hi("TabLineSel", { fg = "#18272B", bg = "#DEE7E4", bold = true })
  hi("TabLineFill", { bg = "#E7EFEB" })
  hi("NonText", { fg = "#C4D2CD" })
  hi("Whitespace", { fg = "#C4D2CD" })
  hi("EndOfBuffer", { fg = "#DEE7E4" })
  hi("Directory", { fg = "#9E5017" })
  hi("Question", { fg = "#4F6855" })
  hi("MoreMsg", { fg = "#4F6855" })
  hi("ErrorMsg", { fg = "#9E5017" })
  hi("WarningMsg", { fg = "#655C7A" })
  hi("FloatBorder", { fg = "#C4D2CD", bg = "#E7EFEB" })
  hi("Cursor", { fg = "#EEF3F0", bg = "#9E5017" })
  hi("DiffAdd", { bg = "#4F6855" })
  hi("DiffDelete", { fg = "#9E5017" })
  hi("DiffChange", { bg = "#E7EFEB" })
  hi("DiffText", { bg = "#B4CCC9" })
  hi("DiagnosticError", { fg = "#9E5017" })
  hi("DiagnosticWarn", { fg = "#655C7A" })
  hi("DiagnosticInfo", { fg = "#3F6274" })
  hi("DiagnosticHint", { fg = "#52646A" })
  hi("@comment", { link = "Comment" })
  hi("@string", { link = "String" })
  hi("@number", { link = "Number" })
  hi("@keyword", { link = "Keyword" })
  hi("@function", { link = "Function" })
  hi("@function.call", { link = "Function" })
  hi("@type", { link = "Type" })
  hi("@constant", { link = "Constant" })
  hi("@variable", { fg = "#18272B" })
  hi("@variable.parameter", { fg = "#2C3C41" })
  hi("@operator", { link = "Operator" })
  hi("@punctuation", { link = "Delimiter" })
  hi("@attribute", { fg = "#7D4C40" })
  hi("@property", { fg = "#18272B" })
  hi("@tag", { fg = "#9E5017", bold = true })
  hi("@markup.heading", { fg = "#9E5017", bold = true })
  hi("@markup.link.url", { fg = "#9E5017", underline = true })
  hi("@markup.raw", { fg = "#4F6855" })

vim.g.terminal_color_0 = "#1B2127"
vim.g.terminal_color_1 = "#C05A3A"
vim.g.terminal_color_2 = "#6F8F6A"
vim.g.terminal_color_3 = "#C9651D"
vim.g.terminal_color_4 = "#46708A"
vim.g.terminal_color_5 = "#8A6F9E"
vim.g.terminal_color_6 = "#5F97A0"
vim.g.terminal_color_7 = "#C9CCCE"
vim.g.terminal_color_8 = "#3A4754"
vim.g.terminal_color_9 = "#D06A52"
vim.g.terminal_color_10 = "#86A87F"
vim.g.terminal_color_11 = "#E0832A"
vim.g.terminal_color_12 = "#5F93B0"
vim.g.terminal_color_13 = "#A487BA"
vim.g.terminal_color_14 = "#8FB6BD"
vim.g.terminal_color_15 = "#F1EFE9"
