// Ambergris 0.3.0 (tokens.json, commit c92c190). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Ambergris.
// Merge into tailwind.config.js, or require() this file and spread it.
module.exports = {
  "theme": {
    "extend": {
      "colors": {
        "grey": {
          "100": "#EAEDEF",
          "200": "#DCDFE3",
          "300": "#C8CBD0",
          "400": "#AEB2B7",
          "500": "#8D9298",
          "600": "#72777D",
          "700": "#5C6168",
          "800": "#42484E",
          "900": "#2B3037",
          "950": "#1A1F26",
          "1000": "#0C1117",
          "000": "#FAFBFD",
          "050": "#F3F5F7"
        },
        "accent": {
          "DEFAULT": "#1E807B",
          "light": "#1E807B",
          "dark": "#5BB6B1"
        },
        "sweep-1": {
          "DEFAULT": "#2EA094",
          "light": "#2EA094",
          "dark": "#13998D"
        },
        "sweep-2": {
          "DEFAULT": "#0587A4",
          "light": "#0587A4",
          "dark": "#2BA6C6"
        },
        "sweep-3": {
          "DEFAULT": "#236AAF",
          "light": "#236AAF",
          "dark": "#6FAEF3"
        },
        "sweep-4": {
          "DEFAULT": "#304BB0",
          "light": "#304BB0",
          "dark": "#A0BAFE"
        },
        "sweep-5": {
          "DEFAULT": "#3428AA",
          "light": "#3428AA",
          "dark": "#C3CCFE"
        },
        "light": {
          "bg": "#FAFBFD",
          "surface": "#EAEDEF",
          "text": "#1A1F26",
          "text-muted": "#5C6168",
          "text-subtle": "#72777D",
          "border": "#C8CBD0",
          "link": "#1E807B",
          "link-hover": "#1B6864",
          "accent": "#2F9F99",
          "on-accent": "#1A1F26",
          "button": "#0C1117",
          "on-button": "#FAFBFD",
          "focus": "#0C1117",
          "selection": "#E7F8F6"
        },
        "dark": {
          "bg": "#1A1F26",
          "surface": "#0C1117",
          "text": "#EAEDEF",
          "text-muted": "#AEB2B7",
          "text-subtle": "#8D9298",
          "border": "#42484E",
          "link": "#5BB6B1",
          "link-hover": "#86CDC8",
          "accent": "#2F9F99",
          "on-accent": "#1A1F26",
          "button": "#EAEDEF",
          "on-button": "#0C1117",
          "focus": "#FAFBFD",
          "selection": "#0E3937"
        }
      }
    }
  }
};
