-- Pequod 0.2.0-alpha (pequod.json, commit 619982d). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Pequod.
-- Save as ~/.config/wezterm/colors/pequod-light.lua; then: config.color_scheme = "Pequod Parchment"
return {
  foreground = "#0D2F42",
  background = "#EAE1D7",
  cursor_bg = "#163F54",
  cursor_fg = "#EAE1D7",
  cursor_border = "#163F54",
  selection_bg = "#DBC9B6",
  selection_fg = "#0D2F42",
  split = "#CFAD8E",
  ansi = { "#0C222F", "#A83732", "#177C55", "#6A4A00", "#0082B1", "#253E82", "#0C7F83", "#835A49" },
  brights = { "#335260", "#893535", "#156D51", "#57450D", "#03719B", "#203B75", "#0C6F76", "#0D2F42" },
  tab_bar = {
    background = "#DBC9B6",
    active_tab = { bg_color = "#EAE1D7", fg_color = "#0D2F42" },
    inactive_tab = { bg_color = "#DBC9B6", fg_color = "#335260" },
    inactive_tab_hover = { bg_color = "#DBC9B6", fg_color = "#0D2F42" },
    new_tab = { bg_color = "#DBC9B6", fg_color = "#335260" },
  },
}
