-- Pequod 0.2.0-alpha (pequod.json, commit 619982d). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Pequod.
-- Copy to ~/.config/nvim/colors/pequod-dark.lua and :colorscheme pequod-dark

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "pequod-dark"

local function hi(group, spec) vim.api.nvim_set_hl(0, group, spec) end

  hi("Normal", { fg = "#EAE1D7", bg = "#0B1720" })
  hi("NormalFloat", { fg = "#EAE1D7", bg = "#0D2F42" })
  hi("NormalNC", { fg = "#EAE1D7", bg = "#0B1720" })
  hi("Comment", { fg = "#BFBBB6", italic = true })
  hi("String", { fg = "#82C4A2" })
  hi("Character", { fg = "#82C4A2" })
  hi("Number", { fg = "#DEC577" })
  hi("Float", { fg = "#DEC577" })
  hi("Boolean", { fg = "#DEC577" })
  hi("Constant", { fg = "#FFD9BB" })
  hi("Identifier", { fg = "#A17069" })
  hi("Function", { fg = "#A6DFFF" })
  hi("Statement", { fg = "#E3877C" })
  hi("Keyword", { fg = "#E3877C" })
  hi("Conditional", { fg = "#E3877C" })
  hi("Repeat", { fg = "#E3877C" })
  hi("Operator", { fg = "#BFBBB6" })
  hi("Exception", { fg = "#E3877C" })
  hi("PreProc", { fg = "#FFD9BB" })
  hi("Include", { fg = "#E3877C" })
  hi("Define", { fg = "#FFD9BB" })
  hi("Macro", { fg = "#FFD9BB" })
  hi("Type", { fg = "#838CCF" })
  hi("StorageClass", { fg = "#E3877C" })
  hi("Structure", { fg = "#838CCF" })
  hi("Typedef", { fg = "#838CCF" })
  hi("Special", { fg = "#FFD9BB" })
  hi("Delimiter", { fg = "#BFBBB6" })
  hi("Todo", { fg = "#0B1720", bg = "#BD8C68", bold = true })
  hi("Underlined", { fg = "#BD8C68", underline = true })
  hi("Error", { fg = "#E3877C" })
  hi("Title", { fg = "#E3877C", bold = true })
  hi("LineNr", { fg = "#A16E50", bg = "#0B1720" })
  hi("CursorLineNr", { fg = "#EAE1D7", bold = true })
  hi("CursorLine", { bg = "#0D2F42" })
  hi("ColorColumn", { bg = "#0D2F42" })
  hi("SignColumn", { bg = "#0B1720" })
  hi("VertSplit", { fg = "#163F54" })
  hi("WinSeparator", { fg = "#163F54" })
  hi("Visual", { bg = "#0D2F42" })
  hi("Search", { fg = "#0B1720", bg = "#BD8C68" })
  hi("IncSearch", { fg = "#0B1720", bg = "#BD8C68" })
  hi("CurSearch", { fg = "#0B1720", bg = "#BD8C68" })
  hi("MatchParen", { fg = "#BD8C68", bold = true, underline = true })
  hi("Pmenu", { fg = "#EAE1D7", bg = "#0D2F42" })
  hi("PmenuSel", { fg = "#EAE1D7", bg = "#0D2F42" })
  hi("PmenuSbar", { bg = "#0D2F42" })
  hi("PmenuThumb", { bg = "#A16E50" })
  hi("StatusLine", { fg = "#EAE1D7", bg = "#0D2F42" })
  hi("StatusLineNC", { fg = "#BD8C68", bg = "#0D2F42" })
  hi("TabLine", { fg = "#BD8C68", bg = "#0D2F42" })
  hi("TabLineSel", { fg = "#EAE1D7", bg = "#0B1720", bold = true })
  hi("TabLineFill", { bg = "#0D2F42" })
  hi("NonText", { fg = "#163F54" })
  hi("Whitespace", { fg = "#163F54" })
  hi("EndOfBuffer", { fg = "#0B1720" })
  hi("Directory", { fg = "#BD8C68" })
  hi("Question", { fg = "#82C4A2" })
  hi("MoreMsg", { fg = "#82C4A2" })
  hi("ErrorMsg", { fg = "#E3877C" })
  hi("WarningMsg", { fg = "#DEC577" })
  hi("FloatBorder", { fg = "#163F54", bg = "#0D2F42" })
  hi("Cursor", { fg = "#0B1720", bg = "#BD8C68" })
  hi("DiffAdd", { bg = "#82C4A2" })
  hi("DiffDelete", { fg = "#E3877C" })
  hi("DiffChange", { bg = "#0D2F42" })
  hi("DiffText", { bg = "#0D2F42" })
  hi("DiagnosticError", { fg = "#E3877C" })
  hi("DiagnosticWarn", { fg = "#DEC577" })
  hi("DiagnosticInfo", { fg = "#A6DFFF" })
  hi("DiagnosticHint", { fg = "#BD8C68" })
  hi("@comment", { link = "Comment" })
  hi("@string", { link = "String" })
  hi("@number", { link = "Number" })
  hi("@keyword", { link = "Keyword" })
  hi("@function", { link = "Function" })
  hi("@function.call", { link = "Function" })
  hi("@type", { link = "Type" })
  hi("@constant", { link = "Constant" })
  hi("@variable", { fg = "#A17069" })
  hi("@variable.parameter", { fg = "#A17069" })
  hi("@operator", { link = "Operator" })
  hi("@punctuation", { link = "Delimiter" })
  hi("@attribute", { fg = "#FFD9BB" })
  hi("@property", { fg = "#A17069" })
  hi("@tag", { fg = "#E3877C" })
  hi("@markup.heading", { fg = "#E3877C", bold = true })
  hi("@markup.link.url", { fg = "#BD8C68", underline = true })
  hi("@markup.raw", { fg = "#82C4A2" })

vim.g.terminal_color_0 = "#0C222F"
vim.g.terminal_color_1 = "#E3877C"
vim.g.terminal_color_2 = "#82C4A2"
vim.g.terminal_color_3 = "#DEC577"
vim.g.terminal_color_4 = "#A6DFFF"
vim.g.terminal_color_5 = "#838CCF"
vim.g.terminal_color_6 = "#9DC2C5"
vim.g.terminal_color_7 = "#EAE1D7"
vim.g.terminal_color_8 = "#335260"
vim.g.terminal_color_9 = "#E99C93"
vim.g.terminal_color_10 = "#AFCCA6"
vim.g.terminal_color_11 = "#E8CB8C"
vim.g.terminal_color_12 = "#A0C2D4"
vim.g.terminal_color_13 = "#AAADDA"
vim.g.terminal_color_14 = "#BCD9DB"
vim.g.terminal_color_15 = "#F7F3EE"
