-- Glauca 0.1.0 (src/glauca.json, commit 1e66632). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Glauca.
-- Copy to ~/.config/nvim/colors/glauca-dark.lua and :colorscheme glauca-dark

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "dark"
vim.g.colors_name = "glauca-dark"

local function hi(group, spec) vim.api.nvim_set_hl(0, group, spec) end

  hi("Normal", { fg = "#E8EEF2", bg = "#10161C" })
  hi("NormalFloat", { fg = "#E8EEF2", bg = "#171F26" })
  hi("NormalNC", { fg = "#E8EEF2", bg = "#10161C" })
  hi("Comment", { fg = "#8C8C8C", italic = true })
  hi("String", { fg = "#62BA46" })
  hi("Character", { fg = "#62BA46" })
  hi("Number", { fg = "#B184DB", italic = true })
  hi("Float", { fg = "#B184DB", italic = true })
  hi("Boolean", { fg = "#B184DB", italic = true })
  hi("Constant", { fg = "#B184DB", italic = true })
  hi("Identifier", { fg = "#E8EEF2" })
  hi("Function", { fg = "#4A9EDB" })
  hi("Statement", { fg = "#007AFF", bold = true })
  hi("Keyword", { fg = "#007AFF", bold = true })
  hi("Conditional", { fg = "#007AFF", bold = true })
  hi("Repeat", { fg = "#007AFF", bold = true })
  hi("Operator", { fg = "#A7B1B8" })
  hi("Exception", { fg = "#007AFF", bold = true })
  hi("PreProc", { fg = "#C96A6A" })
  hi("Include", { fg = "#007AFF", bold = true })
  hi("Define", { fg = "#C96A6A" })
  hi("Macro", { fg = "#C96A6A" })
  hi("Type", { fg = "#45A3AD", italic = true })
  hi("StorageClass", { fg = "#007AFF", bold = true })
  hi("Structure", { fg = "#45A3AD", italic = true })
  hi("Typedef", { fg = "#45A3AD", italic = true })
  hi("Special", { fg = "#B184DB", italic = true })
  hi("Delimiter", { fg = "#86929A" })
  hi("Todo", { fg = "#0B1218", bg = "#3D97FF", bold = true })
  hi("Underlined", { fg = "#3D97FF", underline = true })
  hi("Error", { fg = "#007AFF" })
  hi("Title", { fg = "#007AFF", bold = true })
  hi("LineNr", { fg = "#8C8C8C", bg = "#10161C" })
  hi("CursorLineNr", { fg = "#E8EEF2", bold = true })
  hi("CursorLine", { bg = "#171F26" })
  hi("ColorColumn", { bg = "#171F26" })
  hi("SignColumn", { bg = "#10161C" })
  hi("VertSplit", { fg = "#2A3540" })
  hi("WinSeparator", { fg = "#2A3540" })
  hi("Visual", { bg = "#2B4356" })
  hi("Search", { fg = "#0B1218", bg = "#3D97FF" })
  hi("IncSearch", { fg = "#0B1218", bg = "#3D97FF" })
  hi("CurSearch", { fg = "#0B1218", bg = "#3D97FF" })
  hi("MatchParen", { fg = "#3D97FF", bold = true, underline = true })
  hi("Pmenu", { fg = "#E8EEF2", bg = "#171F26" })
  hi("PmenuSel", { fg = "#E8EEF2", bg = "#2B4356" })
  hi("PmenuSbar", { bg = "#171F26" })
  hi("PmenuThumb", { bg = "#8C8C8C" })
  hi("StatusLine", { fg = "#E8EEF2", bg = "#171F26" })
  hi("StatusLineNC", { fg = "#8C8C8C", bg = "#171F26" })
  hi("TabLine", { fg = "#8C8C8C", bg = "#171F26" })
  hi("TabLineSel", { fg = "#E8EEF2", bg = "#10161C", bold = true })
  hi("TabLineFill", { bg = "#171F26" })
  hi("NonText", { fg = "#2A3540" })
  hi("Whitespace", { fg = "#2A3540" })
  hi("EndOfBuffer", { fg = "#10161C" })
  hi("Directory", { fg = "#3D97FF" })
  hi("Question", { fg = "#62BA46" })
  hi("MoreMsg", { fg = "#62BA46" })
  hi("ErrorMsg", { fg = "#007AFF" })
  hi("WarningMsg", { fg = "#B184DB" })
  hi("FloatBorder", { fg = "#2A3540", bg = "#171F26" })
  hi("Cursor", { fg = "#0B1218", bg = "#007AFF" })
  hi("DiffAdd", { bg = "#62BA46" })
  hi("DiffDelete", { fg = "#007AFF" })
  hi("DiffChange", { bg = "#171F26" })
  hi("DiffText", { bg = "#2B4356" })
  hi("DiagnosticError", { fg = "#007AFF" })
  hi("DiagnosticWarn", { fg = "#B184DB" })
  hi("DiagnosticInfo", { fg = "#4A9EDB" })
  hi("DiagnosticHint", { fg = "#8C8C8C" })
  hi("@comment", { link = "Comment" })
  hi("@string", { link = "String" })
  hi("@number", { link = "Number" })
  hi("@keyword", { link = "Keyword" })
  hi("@function", { link = "Function" })
  hi("@function.call", { link = "Function" })
  hi("@type", { link = "Type" })
  hi("@constant", { link = "Constant" })
  hi("@variable", { fg = "#E8EEF2" })
  hi("@variable.parameter", { fg = "#C3CDD3" })
  hi("@operator", { link = "Operator" })
  hi("@punctuation", { link = "Delimiter" })
  hi("@attribute", { fg = "#C96A6A" })
  hi("@property", { fg = "#E8EEF2" })
  hi("@tag", { fg = "#007AFF", bold = true })
  hi("@markup.heading", { fg = "#007AFF", bold = true })
  hi("@markup.link.url", { fg = "#3D97FF", underline = true })
  hi("@markup.raw", { fg = "#62BA46" })

vim.g.terminal_color_0 = "#171F26"
vim.g.terminal_color_1 = "#B85F5F"
vim.g.terminal_color_2 = "#4F9E3F"
vim.g.terminal_color_3 = "#C79A3D"
vim.g.terminal_color_4 = "#4981C4"
vim.g.terminal_color_5 = "#8E74AB"
vim.g.terminal_color_6 = "#3F93A0"
vim.g.terminal_color_7 = "#C6CED4"
vim.g.terminal_color_8 = "#3A4754"
vim.g.terminal_color_9 = "#C96A6A"
vim.g.terminal_color_10 = "#62BA46"
vim.g.terminal_color_11 = "#D9AE4A"
vim.g.terminal_color_12 = "#007AFF"
vim.g.terminal_color_13 = "#B184DB"
vim.g.terminal_color_14 = "#7FC4CF"
vim.g.terminal_color_15 = "#E8EEF2"
