-- Glauca 0.1.0 (src/glauca.json, commit 1e66632). Generated by Gam, https://gam.tiagojacinto.eu. Tokens CC BY 4.0, attribute Glauca.
-- Copy to ~/.config/nvim/colors/glauca-light.lua and :colorscheme glauca-light

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.o.termguicolors = true
vim.o.background = "light"
vim.g.colors_name = "glauca-light"

local function hi(group, spec) vim.api.nvim_set_hl(0, group, spec) end

  hi("Normal", { fg = "#16222A", bg = "#F0F4F6" })
  hi("NormalFloat", { fg = "#16222A", bg = "#F7FAFB" })
  hi("NormalNC", { fg = "#16222A", bg = "#F0F4F6" })
  hi("Comment", { fg = "#55646D", italic = true })
  hi("String", { fg = "#3C6E38" })
  hi("Character", { fg = "#3C6E38" })
  hi("Number", { fg = "#6B588B", italic = true })
  hi("Float", { fg = "#6B588B", italic = true })
  hi("Boolean", { fg = "#6B588B", italic = true })
  hi("Constant", { fg = "#6B588B", italic = true })
  hi("Identifier", { fg = "#16222A" })
  hi("Function", { fg = "#33668B" })
  hi("Statement", { fg = "#0B62CF", bold = true })
  hi("Keyword", { fg = "#0B62CF", bold = true })
  hi("Conditional", { fg = "#0B62CF", bold = true })
  hi("Repeat", { fg = "#0B62CF", bold = true })
  hi("Operator", { fg = "#55646D" })
  hi("Exception", { fg = "#0B62CF", bold = true })
  hi("PreProc", { fg = "#784A4D" })
  hi("Include", { fg = "#0B62CF", bold = true })
  hi("Define", { fg = "#784A4D" })
  hi("Macro", { fg = "#784A4D" })
  hi("Type", { fg = "#306972", italic = true })
  hi("StorageClass", { fg = "#0B62CF", bold = true })
  hi("Structure", { fg = "#306972", italic = true })
  hi("Typedef", { fg = "#306972", italic = true })
  hi("Special", { fg = "#6B588B", italic = true })
  hi("Delimiter", { fg = "#55646D" })
  hi("Todo", { fg = "#F2F7FB", bg = "#0B62CF", bold = true })
  hi("Underlined", { fg = "#0B62CF", underline = true })
  hi("Error", { fg = "#0B62CF" })
  hi("Title", { fg = "#0B62CF", bold = true })
  hi("LineNr", { fg = "#55646D", bg = "#F0F4F6" })
  hi("CursorLineNr", { fg = "#16222A", bold = true })
  hi("CursorLine", { bg = "#F7FAFB" })
  hi("ColorColumn", { bg = "#F7FAFB" })
  hi("SignColumn", { bg = "#F0F4F6" })
  hi("VertSplit", { fg = "#CDD7DC" })
  hi("WinSeparator", { fg = "#CDD7DC" })
  hi("Visual", { bg = "#B7CDD6" })
  hi("Search", { fg = "#F2F7FB", bg = "#0B62CF" })
  hi("IncSearch", { fg = "#F2F7FB", bg = "#0B62CF" })
  hi("CurSearch", { fg = "#F2F7FB", bg = "#0B62CF" })
  hi("MatchParen", { fg = "#0B62CF", bold = true, underline = true })
  hi("Pmenu", { fg = "#16222A", bg = "#F7FAFB" })
  hi("PmenuSel", { fg = "#16222A", bg = "#B7CDD6" })
  hi("PmenuSbar", { bg = "#F7FAFB" })
  hi("PmenuThumb", { bg = "#55646D" })
  hi("StatusLine", { fg = "#16222A", bg = "#F7FAFB" })
  hi("StatusLineNC", { fg = "#55646D", bg = "#F7FAFB" })
  hi("TabLine", { fg = "#55646D", bg = "#F7FAFB" })
  hi("TabLineSel", { fg = "#16222A", bg = "#F0F4F6", bold = true })
  hi("TabLineFill", { bg = "#F7FAFB" })
  hi("NonText", { fg = "#CDD7DC" })
  hi("Whitespace", { fg = "#CDD7DC" })
  hi("EndOfBuffer", { fg = "#F0F4F6" })
  hi("Directory", { fg = "#0B62CF" })
  hi("Question", { fg = "#3C6E38" })
  hi("MoreMsg", { fg = "#3C6E38" })
  hi("ErrorMsg", { fg = "#0B62CF" })
  hi("WarningMsg", { fg = "#6B588B" })
  hi("FloatBorder", { fg = "#CDD7DC", bg = "#F7FAFB" })
  hi("Cursor", { fg = "#F2F7FB", bg = "#0B62CF" })
  hi("DiffAdd", { bg = "#3C6E38" })
  hi("DiffDelete", { fg = "#0B62CF" })
  hi("DiffChange", { bg = "#F7FAFB" })
  hi("DiffText", { bg = "#B7CDD6" })
  hi("DiagnosticError", { fg = "#0B62CF" })
  hi("DiagnosticWarn", { fg = "#6B588B" })
  hi("DiagnosticInfo", { fg = "#33668B" })
  hi("DiagnosticHint", { fg = "#55646D" })
  hi("@comment", { link = "Comment" })
  hi("@string", { link = "String" })
  hi("@number", { link = "Number" })
  hi("@keyword", { link = "Keyword" })
  hi("@function", { link = "Function" })
  hi("@function.call", { link = "Function" })
  hi("@type", { link = "Type" })
  hi("@constant", { link = "Constant" })
  hi("@variable", { fg = "#16222A" })
  hi("@variable.parameter", { fg = "#2C3941" })
  hi("@operator", { link = "Operator" })
  hi("@punctuation", { link = "Delimiter" })
  hi("@attribute", { fg = "#784A4D" })
  hi("@property", { fg = "#16222A" })
  hi("@tag", { fg = "#0B62CF", bold = true })
  hi("@markup.heading", { fg = "#0B62CF", bold = true })
  hi("@markup.link.url", { fg = "#0B62CF", underline = true })
  hi("@markup.raw", { fg = "#3C6E38" })

vim.g.terminal_color_0 = "#0B1218"
vim.g.terminal_color_1 = "#A55859"
vim.g.terminal_color_2 = "#3F7B39"
vim.g.terminal_color_3 = "#846C36"
vim.g.terminal_color_4 = "#4070A8"
vim.g.terminal_color_5 = "#786594"
vim.g.terminal_color_6 = "#357884"
vim.g.terminal_color_7 = "#3E4D55"
vim.g.terminal_color_8 = "#55646D"
vim.g.terminal_color_9 = "#B06061"
vim.g.terminal_color_10 = "#47833C"
vim.g.terminal_color_11 = "#87733D"
vim.g.terminal_color_12 = "#0273EE"
vim.g.terminal_color_13 = "#8669A9"
vim.g.terminal_color_14 = "#517D86"
vim.g.terminal_color_15 = "#16222A"
